SET SCHEMA "CONTRACT_MANAGEMENT";
DROP VIEW "V_RA_DAILY_DETAIL_WORKERS";
DROP VIEW "V_RA_DAILY_DETAIL_VEHICLE";
DROP VIEW "V_RA_DAILY_DETAIL_EQUIPMENT";
DROP VIEW "V_RA_DAILY_DETAIL_WORKER_NONCORE";
DROP VIEW "V_RA_DAILY_DETAIL_VEHICLE_NONCORE";
DROP VIEW "V_RA_DAILY_DETAIL_EQUIPMENT_NONCORE";

-- Creazione view ra daily detail workers
CREATE VIEW "V_RA_DAILY_DETAIL_WORKERS"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDW."UUID_RA_DAILY_DETAIL_WORKER" AS "UuidRaDailyDetailWorker",
	    RDDW."ID_WORKER" AS "IdWorker",
	    RDDW."TIME1_BEG" AS "Time1Beg",
	    RDDW."TIME1_END" AS "Time1End",
	    RDDW."TIME2_BEG" AS "Time2Beg",
	    RDDW."TIME2_END" AS "Time2End",
	    RDDW."TIME_BREAK" AS "TimeBreak",
	    RDDW."TOTAL_HOURS" AS "TotalHours",
	    RDDW."CREATED_AT" AS "CreatedAt",
	    RDDW."CREATED_BY" AS "CreatedBy",
		RDDW."IS_DELETED" AS "IsDeleted",

	    W."NAME" AS "name",
	    W."SURNAME" AS "surname",
	    W."CONTRACT_EXPIRED_DATE" AS "contractExpiredDate"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_WORKER" as RDDW on RDD."UUID_RA_DAILY_DETAIL" = RDDW."UUID_RA_DAILY_DETAIL"
		JOIN "CONTRACT_MANAGEMENT"."WORKERS" as W on RDDW."ID_WORKER" = W."ID_WORKER";
		
-- Creazione view ra daily detail vehicle
CREATE VIEW "V_RA_DAILY_DETAIL_VEHICLE"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDV."UUID_RA_DAILY_DETAIL_VEHICLE" AS "UuidRaDailyDetailVehicle",
	    RDDV."ID_VEHICLE" AS "IdVehicle",
	    RDDV."TIME1_BEG" AS "Time1Beg",
	    RDDV."TIME1_END" AS "Time1End",
	    RDDV."TIME2_BEG" AS "Time2Beg",
	    RDDV."TIME2_END" AS "Time2End",
	    RDDV."TIME_BREAK" AS "TimeBreak",
	    RDDV."TOTAL_HOURS" AS "TotalHours",
	    RDDV."CREATED_AT" AS "CreatedAt",
	    RDDV."CREATED_BY" AS "CreatedBy",
		RDDV."IS_DELETED" AS "IsDeleted",
		
	    V."BRAND" AS "Brand"
		
		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_VEHICLE" as RDDV on RDD."UUID_RA_DAILY_DETAIL" = RDDV."UUID_RA_DAILY_DETAIL"
		JOIN "CONTRACT_MANAGEMENT"."VEHICLES" as V on RDDV."ID_VEHICLE" = V."ID_VEHICLES";			
		
-- Creazione view ra daily detail equipment
CREATE VIEW "V_RA_DAILY_DETAIL_EQUIPMENT"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDE."UUID_RA_DAILY_DETAIL_EQUIPMENT" AS "UuidRaDailyDetailEquipment",
	    RDDE."ID_EQUIPMENT" AS "IdEquipment",
	    RDDE."TIME1_BEG" AS "Time1Beg",
	    RDDE."TIME1_END" AS "Time1End",
	    RDDE."TIME2_BEG" AS "Time2Beg",
	    RDDE."TIME2_END" AS "Time2End",
	    RDDE."TIME_BREAK" AS "TimeBreak",
	    RDDE."TOTAL_HOURS" AS "TotalHours",
	    RDDE."CREATED_AT" AS "CreatedAt",
	    RDDE."CREATED_BY" AS "CreatedBy",
		RDDE."IS_DELETED" AS "IsDeleted",
	    E."DESCRIPTION" AS "Description",
	    E."MANUFACTURER" AS "Manufacturer",
	    E."MODEL" AS "Model"
		
		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_EQUIPMENT" as RDDE on RDD."UUID_RA_DAILY_DETAIL" = RDDE."UUID_RA_DAILY_DETAIL"
		JOIN "CONTRACT_MANAGEMENT"."EQUIPMENT" as E on RDDE."ID_EQUIPMENT" = E."ID_EQUIPMENT";

-- Creazione view ra non core worker
CREATE VIEW "V_RA_DAILY_DETAIL_WORKER_NONCORE"    
AS
	SELECT DISTINCT
	    RDDWNS."UUID_RA_DAILY_HEAD_WORKER" AS "UUID_RA_DAILY_HEAD_WORKER",
	    RDDWNS."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
	    RDDWNS."ID_WORKER" AS "ID_WORKER",
	    RDDWNS."TIME1_BEG" AS "TIME1_BEG",
	    RDDWNS."TIME1_END" AS "TIME1_END",
	    RDDWNS."TIME2_BEG" AS "TIME2_BEG",
	    RDDWNS."TIME2_END" AS "TIME2_END",
	    RDDWNS."TIME_BREAK" AS "TIME_BREAK",
	    RDDWNS."CREATED_AT" AS "CREATED_AT",
	    RDDWNS."CREATED_BY" AS "CREATED_BY",
		RDDWNS."IS_DELETED" AS "IsDeleted",
		RDDWNS.TOTAL_HOURS  AS "TOTAL_HOURS", 
	    
	    W."NAME" AS "NAME",
	    W."SURNAME" AS "SURNAME"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_WORKER_NONCORE_SERVICES" as RDDWNS
		JOIN "CONTRACT_MANAGEMENT"."WORKERS" as W on RDDWNS."ID_WORKER" = W."ID_WORKER";
		
-- Creazione view ra non core vehicle
CREATE VIEW "V_RA_DAILY_DETAIL_VEHICLE_NONCORE"    
AS
	SELECT DISTINCT
	    RDDVNS."UUID_RA_DAILY_HEAD_VEHICLE" AS "UUID_RA_DAILY_HEAD_VEHICLE",
	    RDDVNS."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
	    RDDVNS."ID_VEHICLE" AS "ID_VEHICLE",
	    RDDVNS."TIME1_BEG" AS "TIME1_BEG",
	    RDDVNS."TIME1_END" AS "TIME1_END",
	    RDDVNS."TIME2_BEG" AS "TIME2_BEG",
	    RDDVNS."TIME2_END" AS "TIME2_END",
	    RDDVNS."TIME_BREAK" AS "TIME_BREAK",
	    RDDVNS."CREATED_AT" AS "CREATED_AT",
	    RDDVNS."CREATED_BY" AS "CREATED_BY",
		RDDVNS."IS_DELETED" AS "IsDeleted",
		RDDVNS.TOTAL_HOURS  AS "TOTAL_HOURS", 
	    
	    V."BRAND" AS "BRAND"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_VEHICLE_NONCORE_SERVICES" as RDDVNS
		JOIN "CONTRACT_MANAGEMENT"."VEHICLES" as V on RDDVNS."ID_VEHICLE" = V."ID_VEHICLES";

-- Creazione view ra non core equipment
CREATE VIEW "V_RA_DAILY_DETAIL_EQUIPMENT_NONCORE"    
AS
	SELECT DISTINCT
	    RDDENS."UUID_RA_DAILY_HEAD_EQUIPMENT" AS "UUID_RA_DAILY_HEAD_EQUIPMENT",
	    RDDENS."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
	    RDDENS."ID_EQUIPMENT" AS "ID_EQUIPMENT",
	    RDDENS."TIME1_BEG" AS "TIME1_BEG",
	    RDDENS."TIME1_END" AS "TIME1_END",
	    RDDENS."TIME2_BEG" AS "TIME2_BEG",
	    RDDENS."TIME2_END" AS "TIME2_END",
	    RDDENS."TIME_BREAK" AS "TIME_BREAK",
	    RDDENS."CREATED_AT" AS "CREATED_AT",
	    RDDENS."CREATED_BY" AS "CREATED_BY",
		RDDENS."IS_DELETED" AS "IsDeleted",
		RDDENS.TOTAL_HOURS  AS "TOTAL_HOURS", 
	    
	    E."DESCRIPTION" AS "DESCRIPTION"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_EQUIPMENT_NONCORE_SERVICES" as RDDENS
		JOIN "CONTRACT_MANAGEMENT"."EQUIPMENT" as E on RDDENS."ID_EQUIPMENT" = E."ID_EQUIPMENT";	
