CREATE TYPE "CONTRACT_MANAGEMENT"."TT_ERROR" AS TABLE  ( "HTTP_STATUS_CODE" INT CS_INT, "ERROR_MESSAGE" NVARCHAR(100)  CS_STRING, "DETAIL" NVARCHAR(100)  CS_STRING );

CREATE TYPE "CONTRACT_MANAGEMENT"."TT_OUT" AS TABLE  ( "ESITO" NVARCHAR(2)  CS_STRING, "MSG" NVARCHAR(50)  CS_STRING );
