/* Run the scripts manually */
/* Suppliers */
CREATE TRIGGER "CONTRACT_MANAGEMENT"."SUPPLIERS_TRIGGER_BEF_INST" BEFORE INSERT ON "CONTRACT_MANAGEMENT"."SUPPLIERS" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN

	DECLARE VAR_ID INT;
    
    SELECT TO_NUMBER("CONTRACT_MANAGEMENT"."SUPPLIERS_SEQ".NEXTVAL)
    INTO VAR_ID
    FROM DUMMY;
    
    MYNEWROW.ID_UNIQUE_SUP = :VAR_ID;
END;

/* Attachments */
CREATE TRIGGER "CONTRACT_MANAGEMENT"."ATTACHMENTS_TRIGGER_BEF_INST" BEFORE INSERT ON "CONTRACT_MANAGEMENT"."ATTACHMENTS" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN

	DECLARE VAR_ID INT;
    
    SELECT TO_NUMBER("CONTRACT_MANAGEMENT"."ATTACHMENTS_SEQ".NEXTVAL)
    INTO VAR_ID
    FROM DUMMY;
    
    MYNEWROW.ID_ATTACHMENT = :VAR_ID;
    
    INSERT INTO "CONTRACT_MANAGEMENT"."REL_DOCUMENT_ATTACHMENTS" VALUES( :MYNEWROW.ID_DOCUMENT, :MYNEWROW.ID_ATTACHMENT, :MYNEWROW.UPLOAD_FROM, :MYNEWROW.ID_CONTRACT, '' );

END;

/* Contract Association Details */
CREATE TRIGGER "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATION_DETAILS_TRIGGER_BEF_INST" BEFORE INSERT ON "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATION_DETAILS" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN

	DECLARE VAR_ID INT;

	SELECT TO_NUMBER("CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATION_DETAILS_SEQ".NEXTVAL)
	INTO VAR_ID
	FROM DUMMY;

	MYNEWROW.ID_CONTRACT_ASSOCIATION_DETAIL = :VAR_ID;        
END

/* Contract Associations */
CREATE TRIGGER "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATIONS_TRIGGER_BEF_INST" BEFORE INSERT ON "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATIONS" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN

	DECLARE VAR_ID INT;

	SELECT TO_NUMBER("CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATIONS_SEQ".NEXTVAL)
	INTO VAR_ID
	FROM DUMMY;

	MYNEWROW.ID_CONTRACT_ASSOCIATION = :VAR_ID;        
END

/* Documents */
CREATE TRIGGER "CONTRACT_MANAGEMENT"."DOCUMENTS_TRIGGER_BEF_INST" BEFORE INSERT ON "CONTRACT_MANAGEMENT"."DOCUMENTS" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN

	DECLARE VAR_ID INT;

	SELECT TO_NUMBER("CONTRACT_MANAGEMENT"."DOCUMENTS_SEQ".NEXTVAL)
	INTO VAR_ID
	FROM DUMMY;

	MYNEWROW.ID_DOCUMENT = :VAR_ID;        
END

/* Green Sheets */
CREATE TRIGGER "CONTRACT_MANAGEMENT"."GREEN_SHEETS_TRIGGER_BEF_INST" BEFORE INSERT ON "CONTRACT_MANAGEMENT"."GREEN_SHEETS" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN

	DECLARE VAR_ID INT;

	SELECT TO_NUMBER("CONTRACT_MANAGEMENT"."GREEN_SHEETS_SEQ".NEXTVAL)
	INTO VAR_ID
	FROM DUMMY;

	MYNEWROW.ID_GREEN_SHEET = :VAR_ID;        
END

/* REL_USER_UB */
CREATE TRIGGER "CONTRACT_MANAGEMENT"."REL_USER_UB_TRIGGER_BEF_INST" BEFORE INSERT ON "CONTRACT_MANAGEMENT"."REL_USER_UB" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN

	DECLARE VAR_ID INT;
    
    SELECT TO_NUMBER("CONTRACT_MANAGEMENT"."REL_USER_UB_SEQ".NEXTVAL)
    INTO VAR_ID
    FROM DUMMY;
    
    MYNEWROW.ID_REL_USER_UB = :VAR_ID;

END;

------------- APP GROUP MANAGEMENT ----------------
/* Groups */
CREATE TRIGGER "CONTRACT_MANAGEMENT"."GROUP_TRIGGER_BEF_INST" BEFORE INSERT ON "CONTRACT_MANAGEMENT"."GROUPS" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN

	DECLARE VAR_ID INT;

	SELECT TO_NUMBER("CONTRACT_MANAGEMENT"."GROUPS_SEQ".NEXTVAL)
	INTO VAR_ID
	FROM DUMMY;

	MYNEWROW.ID_GROUP = :VAR_ID;        
END