-- inserimento documenti comuni anagraf. forn/contr doc amministrativi
INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 1,'PR-0000105531',1,'Iscrizione alla camera di commercio, industria ed artigianato ', 'Iscrizione alla camera di commercio, industria ed artigianato con oggetto sociale inerente alla tipologia dell’appalto o autocertificazione in sostituzione.', '', 'COM', '');
INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 2,'PR-0000105531',1,'Documento di regolarità contributiva (DURC)', 'Documento di regolarità contributiva (DURC in originale) in corso di validità (documento del tipo previsto per appalti di lavori pubblici; il documento deve essere rinnovato e riconsegnato ad ogni scadenza, 4 mesi, per tutto il periodo di gestione del contratto); In caso di presenza di lavoratori in somministrazione/distacco l’Appaltatore dovrà fornire il DURC anche per questi lavoratori, facendo da tramite con i relativi datori di lavoro', '', 'COM', '');
INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 3,'PR-0000105531',1,'Polizza assicurativa', 'Polizza assicurativa, con relativa quietanza di pagamento premio, contro danni a persone e cose di Enel/impresa/terzi, con rinuncia da parte della società assicuratrice al diritto di rivalsa nei confronti di Enel; la polizza dovrà riportare la seguente dichiarazione: “Questa compagnia di Assicurazione fa espressa rinuncia al diritto di rivalsa nei confronti dell’Enel. La presente polizza copre l’assicurato contro tutti i danni alle persone ed alle cose anche di sua proprietà”', '', 'COM', '');
INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 4,'PR-0000105531',1,'Richiesta di ingresso in centrale per dipendenti, mezzi e attrezzature', 'Richiesta di ingresso in centrale per dipendenti, mezzi e attrezzature', '', 'COM', '');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 5,'PR-0000105531',1,'Assegnazione nomine contratto', 'Comunicazione del Vs. indirizzo di posta elettronica (e-mail), con esplicito consenso all’utilizzo di tale mezzo da parte di Enel per inoltrarVi le varie comunicazioni/documentazioni che si renderanno necessari.', '', 'COM', '');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 6,'PR-0000105531',1,'Denuncia enti previdenziali', 'Copia della documentazione di avvenuta denuncia agli Enti previdenziali, assicurativi ed infortunistici concernente il contratto in oggetto, come previsto all art. 105 - comma 9 – D.Lgs 50/2016 o autocertificazione in sostituzione', '', 'COM', '');
-- inserimento documenti comuni anagraf. forn/contr doc salute e sicurezza
INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 7, 'PR-0000105531',2,'Dichiar. conformità attrezzature', 'Elenco delle attrezzature introdotte in centrale. L’elenco dovrà essere corredato di una Dichiarazione firmata dal Datore di lavoro o Legale Rappresentante della ditta, rilasciata ai sensi dell’art. 47 del DPR 445/2000, attestante che le attrezzature di lavoro che si prevede di utilizzare presso il sito Enel siano: conformi alle disposizione del D. Lgs. 81/08 e, ove previsto dalla vigente normativa, sono corredate di dichiarazione CE di conformità; rispondenti alle disposizioni vigenti in materia di prevenzione degli infortuni sul lavoro e vengono regolarmente verificate e mantenute secondo le modalità prescritte nei relativi libretti d’uso e manutenzione; utta la documentazione inerente il macchinario/attrezzatura dovrà esser a disposizione presso il Cantiere', '', 'COM', '');
INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 8, 'PR-0000105531',2,'Dichiar. formazione lavoratori', 'Dichiarazione firmata dal Legale Rappresentante ai sensi dell’art. 47 del DPR 445/2000 attestante la formazione dei propri lavoratori e tabulato riepilogativo requisiti e attestazioni in possesso dei singoli lavoratori (vedi All.19).A13', '', 'COM', '');
INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 9, 'PR-0000105531',2,'Dichiar. idoneità tecnico-professionali lavoratori', 'Dichiarazione rilasciata dall’appaltatore ai sensi dell’art. 47 del DPR 445/2000 di possesso di requisiti di idoneità tecnico-professionale richiesti dall’art. 26 comma 1 punto a del D.lgs 81/08 (ovvero art. 90 comma 9 punto a. del titolo IV per cantieri temporanei e mobili); ', '', 'COM', '');
INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 10,'PR-0000105531',2,'Dichiar. idoneità sanitaria lavoratori', 'Elenco dei lavoratori da impiegare per le attività e relativa idoneità sanitaria - Dichiarazione del Datore di lavoro comprovante l’idoneità sanitaria dei lavoratori per le mansioni specifiche ', '', 'COM', '');
INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 11,'PR-0000105531',2,'Dichiar. formazione uso DPI lavoratori', 'Dichiarazione firmata dal Rappresentante Legale ai sensi dell’art. 47 del DPR 445/2000, che i lavoratori sono stati dotati e formati sull’utilizzo dei DPI.', '', 'COM', '');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 12,'PR-0000105531',2,'Documento di valutazione dei rischi per le specifiche attività oggetto del appalto', 'Documento di valutazione dei rischi per le specifiche attività oggetto del appalto, redatto dall’appaltatore ai sensi dell’art. 17, comma 1 lettera a, ed art 28 del D.Lgs. 81/08, che vale anche in ottemperanza all’art. 105 - comma 17 – del D.Lgs 50/2016 (ovvero Piano Operativo di sicurezza qualora le attività siano svolte ai sensi del Titolo IV del D.Lgs 81/08); ', '', 'COM', '');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 13,'PR-0000105531',2,'Dichiar. assegnazione nomine contratto', 'Dichiarazione, firmata dal Rappresentante Legale ai sensi dell’art. 47 del DPR 445/2000, attestante la nomina di RSPP, RLS, incaricati dell’attuazione delle misure di prevenzione incendi e lotta antincendio, incaricati delle misure di evacuazione, incaricati del primo soccorso e gestione dell’emergenza, del preposto, del medico competente, del capocantiere e del vice capocantiere', '', 'COM', '');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 14,'PR-0000105531',2,'Elenco sostanze chimiche', 'Elenco delle sostanze chimiche eventualmente utilizzate in cantiere e relative Schede di Sicurezza; le sostanze sono soggette ad autorizzazione in conformità alle procedure vigenti nelle UB.', '', 'COM', '');
-- inserimento documenti comuni anagraf. forn/contr doc personale
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 15, 'PR-0000105531',4,'Elenco DPI lavoratore', 'Elenco dei dispositivi di protezione individuali forniti ai lavoratori', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 16, 'PR-0000105531',4,'Qualifica CEI', 'Qualifica PES/PEI/PAV se presente, con certificato allegato (personale da impiegare qualora le attività di pertinenza comportino rischi di natura elettrica, conformemente alla Norma CEI EN50110)', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 17, 'PR-0000105531',4,'Carta di identità', 'Carta di identità', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 18, 'PR-0000105531',4,'Permesso di soggiorno', 'Per i lavoratori extracomunitari, fotocopia leggibile del permesso di soggiorno', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 19, 'PR-0000105531',4,'Idoneità sanitaria', 'Idoneità sanitaria con scadenza', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 20, 'PR-0000105531',4,'Fototessera', 'Fototessera', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 21, 'PR-0000105531',4,'Copia libro matricola', 'Copia del libro matricola (completo della parte destra) per dipendenti assunti prima del 2008 o copia del Libro Unico del Lavoro (per dipendenti assunti dopo il 2008) per la parte che riguarda qualifica e date di assunzione e scadenza contratto individuale, UNILAV; o autocertificazione in sostituzione', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 22, 'PR-0000105531',4,'Contratto', 'Tipologia di contratto', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 23, 'PR-0000105531',4,'Contratto a tempo determinato', 'Se tempo determinato, inserire scadenza', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 24, 'PR-0000105531',4,'Contratto di distacco: Comunicazione impresa', 'Comunicazione formale dell impresa appaltatrice ad Enel di volersi avvalere di personale in distacco temporaneo da altra impresa, con specificazione dell impresa distaccante e delle generalità del personale distaccato;', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 25, 'PR-0000105531',4,'Contratto di distacco: Dichiarazione distaccante', 'Dichiarazione dell impresa distaccante contenente l indicazione dell impresa beneficiaria del distacco, delle generalità del personale distaccato, della temporaneità del distacco e delle attività cui è destinato il personale distaccato;', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 26, 'PR-0000105531',4,'Contratto di distacco: DURC', 'Certificazione che attesti la regolarità contributiva dell impresa distaccante (Durc)', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 27, 'PR-0000105531',4,'Contratto di distacco: Accettazione distacco', 'Accettazione del lavoratore distaccato in merito a quanto concordato tra impresa cedente e impresa ricevente', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 28, 'PR-0000105531',4,'Contratto di distacco: Copia libro matricola', 'Copia Libro Unico del Lavoro del personale distaccato', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 29, 'PR-0000105531',4,'Quallifica Subacqueo', 'Attestato di qualifica professionale di Operatore Tecnico Subacqueo (OTS)[1], ovvero di un livello di formazione professionale superiore a quello di OTS conseguito a seguito della frequenza di corsi che hanno ottenuto il riconoscimento H.S.E. (Health and Safety Executive); iscrizione nel Registro dei Sommozzatori in servizio locale; idoneità fisica alla mansione di sommozzatore rilasciata dallo specialista medico subacqueo[2] con periodicità di legge ', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 30, 'PR-0000105531',4,'Qualifica Sollevamenti', 'Adibitazione all’uso di attrezzature che richiedono specifica formazione/addestramento (ad. es. piattaforme di lavoro mobili elevabili, gru a torre, gru mobile, gru per autocarro, carrelli elevatori semoventi con conducente a bordo, macchine movimento terra – escavatori idraulici, a fune, pale caricatrici frontali, terne, autoribaltabili a cingoli, ecc)', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 31, 'PR-0000105531',4,'Qualifica Ponteggiatori', 'Formazione teorico-pratico per lavoratori e preposti addetti al montaggio/smontaggio/trasformazione dei ponteggi (art. 136, All. XXI D.Lgs. 81/2008 e smi)', '', 'COM');
-- INSERT INTO "CONTRACT_MANAGEMENT"."DOCUMENTS" VALUES( 32, 'PR-0000105531',4,'Qualifica accesso luoghi confinati', 'attestazioni, firmate dai lavoratori, dell’avvenuta attività informative, formative e di addestramento ai sensi dell’art. 47 del DPR 445/2000; di essere in possesso di tutti i requisiti previsti per l’esecuzione delle attività di cui all’art 2 del DPR. 177/2011.', '', 'COM');