INSERT INTO "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS_T" VALUES(1,'IT', 'Da Convalidare');
INSERT INTO "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS_T" VALUES(2,'IT', 'Convalidato');
INSERT INTO "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS_T" VALUES(3,'IT', 'Rifiutato');
INSERT INTO "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS_T" VALUES(4,'IT', 'Convalidato (Forzato)');