INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES" VALUES(1, 1);
INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES" VALUES(2, 2);
INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES" VALUES(3, 3);
INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES" VALUES(4, 4);
INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES" VALUES(5, 5);