INSERT INTO "CONTRACT_MANAGEMENT"."WORKER_CONTRACT_TYPES_T" VALUES(1,'IT', 'INDETERMINATO');
INSERT INTO "CONTRACT_MANAGEMENT"."WORKER_CONTRACT_TYPES_T" VALUES(2,'IT', 'DETERMINATO');
INSERT INTO "CONTRACT_MANAGEMENT"."WORKER_CONTRACT_TYPES_T" VALUES(3,'IT', 'DISTACCO');