INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES_T" VALUES(0,'IT', '');
INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES_T" VALUES(1,'IT', 'Mezzi trasporto persone e movimentazione materiali (autocarro)');
INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES_T" VALUES(2,'IT', 'Autocarro con gru'); 
INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES_T" VALUES(3,'IT', 'Piattaforme aeree');
INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES_T" VALUES(4,'IT', 'Ponti mobili sviluppabili');
INSERT INTO "CONTRACT_MANAGEMENT"."VEHICLES_TYPES_T" VALUES(5,'IT', 'Macchine operatrici');