INSERT INTO "CONTRACT_MANAGEMENT"."WORKER_CONTRACT_TYPES" VALUES(1, 1);
INSERT INTO "CONTRACT_MANAGEMENT"."WORKER_CONTRACT_TYPES" VALUES(2, 2);
INSERT INTO "CONTRACT_MANAGEMENT"."WORKER_CONTRACT_TYPES" VALUES(3, 3);