-- inserimento documenti comuni anagraf. forn/contr doc amministrativi
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 1, 1,'Iscrizione alla camera di commercio, industria ed artigianato ', 'Iscrizione alla camera di commercio, industria ed artigianato con oggetto sociale inerente alla tipologia dell’appalto.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 2, 1,'Documento di regolarità contributiva (DURC)', 'Documento di regolarità contributiva (DURC in originale) in corso di validità (documento del tipo previsto per appalti di lavori pubblici; il documento deve essere rinnovato e riconsegnato ad ogni scadenza, 3 mesi, per tutto il periodo di gestione del contratto); In caso di presenza di lavoratori in somministrazione/distacco l’appaltatore/subappaltatore dovrà fornire il DURC anche per questi lavoratori, facendo da tramite con i relativi datori di lavoro', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 3, 1,'Polizza assicurativa', 'Polizza assicurativa, con relativa quietanza di pagamento premio, contro danni a persone e cose di Enel/impresa/terzi, con rinuncia da parte della società assicuratrice al diritto di rivalsa nei confronti di Enel; la polizza dovrà riportare la seguente dichiarazione: “Questa compagnia di Assicurazione fa espressa rinuncia al diritto di rivalsa nei confronti dell’Enel. La presente polizza copre l’assicurato contro tutti i danni alle persone ed alle cose anche di sua proprietà”', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 4, 5,'Richiesta di ingresso in centrale per dipendenti', 'Richiesta di ingresso in centrale per dipendenti e mezzi corredato con le informazioni relative a: nome e cognome; residenza; qualifica; tipologia di contratto; se il lavoratore è a tempo determinato precisare data scadenza contratto; aggiungere, inoltre, i seguenti dati relativi all’impresa: numero di posizione assicurativa INPS; numero di posizione assicurativa INAIL; estremi posizione assicurativa territoriale INAIL; eventuale Cassa Edile;', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 5, 5,'Richiesta di ingresso in centrale per mezzi', 'Richiesta di ingresso in centrale per dipendenti, mezzi e attrezzature ', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 6, 5,'Richiesta di ingresso in centrale per attrezzature', 'Richiesta di ingresso in centrale per dipendenti, mezzi e attrezzature ', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 7, 5,'Denuncia enti previdenziali', 'Copia della documentazione di avvenuta denuncia agli Enti previdenziali, assicurativi ed infortunistici concernente il contratto in oggetto, come previsto all art. 105 - comma 9 – D.Lgs 50/2016', '');
-- INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 8, 5,'Indirizzo mail appaltatore', 'Comunicazione del Vs. indirizzo di posta elettronica (e-mail), con esplicito consenso all’utilizzo di tale mezzo da parte di Enel per inoltrarVi le varie comunicazioni/documentazioni che si renderanno necessari.', '');
-- inserimento documenti comuni anagraf. forn/contr doc salute e sicurezza
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 9, 2,'Dichiar. requisiti luoghi confinati', 'In caso di attività lavorative in ambienti sospetti di inquinamento o confinati: Dichiarazione firmata dal Rappresentante Legale ai sensi dell’art. 47 del DPR 445/2000 di essere in possesso di tutti i requisiti previsti per l’esecuzione delle attività di cui all’art 2 del DPR. 177/2011. Alla dichiarazione allegare le attestazioni, firmate dai lavoratori, dell’avvenuta attività informative, formative e di addestramento', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 10, 2,'Elenco sostanze chimiche', 'Elenco delle sostanze chimiche eventualmente utilizzate in cantiere e relative Schede di Sicurezza; le sostanze sono soggette ad autorizzazione in conformità alle procedure vigenti nelle UB.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 11, 2,'DVRI programmatico', 'DVRI programmatico con Timbro e firma dell’appaltatore/subappaltatore; nel caso di RTI – Consorzio -  subappalto timbro e firma di ciascuna impresa a seguito della condivisione del DUVRI ed elaborazione delle “Misure di protezione e prevenzione per la riduzione del rischio di interferenza dei lavoratori dell’RTI (o Consorzio e/o subappaltatori)', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 12, 2,'Dichiar. per imprese famigliari e lavoratori autonomi', 'Nel caso di imprese familiari e lavoratori autonomi integrale e vincolante applicazione del comma 2 art. 21 DLgs 81/08.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 13, 6,'Dichiar. in materia di salute e sicurezza sul lavoro', 'Dichiarazione firmata dal Legale Rappresentante ai sensi dell’art. 47 del DPR 445/2000 attestante: - Che i propri dipendenti sono stati formati ed informati sui rischi specifici connessi alle attività oggetto dell’Appalto conformemente a quanto previsto dall’art 36 D.Lgs 81/08 e s.m.i.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 14, 6,'Documento di valutazione dei rischi per le specifiche attività oggetto dell appalto', 'Documento di valutazione dei rischi per le specifiche attività oggetto del appalto/subappalto, redatto dall’appaltatore/subappaltatore ai sensi dell’art. 17, comma 1 lettera a, ed art 28 del D.Lgs. 81/08, che vale anche in ottemperanza all’art. 105 - comma 17 – del D.Lgs 50/2016 (ovvero Piano Operativo di sicurezza qualora le attività siano svolte ai sensi del Titolo IV del D.Lgs 81/08); ', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 15, 6,'Elenco dei lavoratori da impiegare per le attività oggetto dell appalto', 'Elenco dei lavoratori da impiegare per le attività e relativa idoneità sanitaria (nel caso di attività in luoghi confinati il medico competente dovrà valutare tale fattore di rischio riportandolo sull’idoneità sanitaria) – Compilare allegato 3 e allegare copia delle singole idoneità sanitarie.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 16, 6,'Piano di sicurezza per l accesso e la permaneneza delle persone nei luoghi confinati', 'In caso di attività lavorative in ambienti sospetti di inquinamento o confinati: Piano di sicurezza per l’accesso e la permanenza delle persone nei luoghi confinati redatto in relazione alle specifiche attività oggetto dell’appalto/subappalto', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 17, 6,'Dichiarazione ed attestato di sopralluogo preventivo', 'Dichiarazione ed attestato di sopralluogo preventivo (trasmettere copia “Allegato F” se sottoscritto in fase di gara, oppure da redigersi in occasione del primo accesso in impianto) con timbro e firma del appaltatore/subappaltatore; nel caso di ATI – Consorzio -  subappalto, dichiarazione ed attestato di sopralluogo preventivo con timbro e firma di ciascuna impresa.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 18, 6,'Tabella riepilogativa requisiti attestazioni in possesso dei dipendenti', 'Compilare a cura appaltatore/subappaltatore, Tabulato riepilogativo - file Excel - Requisiti e attestazioni in possesso dei dipendenti', '');

-- inserimento documenti comuni anagraf. forn/contr doc personale
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 19, 4,'Copia libro matricola', 'Copia del libro matricola (completo della parte destra) o copia del Libro Unico del Lavoro per la parte che riguarda qualifica e date di assunzione e scadenza contratto individuale, UNILAV.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 20, 4,'Documento di identità', 'Scansione leggibile di un documento di identità', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 21, 4,'Fototessera', 'Foto formato tessera (o scansione a colori della tessera di riconoscimento) in formato JPEG per l’emissione del cartellino di ingresso.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 22, 4,'Permesso di soggiorno', 'Per i lavoratori extracomunitari, fotocopia leggibile del permesso di soggiorno', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 23, 4,'Dichiarazione contratto collettivo del lavoratore', 'Dichiarazione relativa al contratto collettivo applicato ai lavoratori dipendenti.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 24, 4,'Registro corso di informazione rischi specifici appalto', 'Registro riportante che i propri dipendenti sono stati formati ed informati sui rischi specifici connessi alle attività oggetto dell’Appalto conformemente a quanto previsto dall’art 36 D.Lgs 81/08 e s.m.i. (Alla dichiarazione dovranno essere allegati gli attestati (registri) dei corsi effettuati riportante la firma dei lavoratori)', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 25, 4,'Registro elenco DPI forniti al lavoratore e relativa formazione all utilizzo', 'Registro riportante che i lavoratori sono stati dotati e formati sull’utilizzo dei DPI. (Alla dichiarazione allegare l’elenco dei dispositivi di protezione individuali forniti ai lavoratori e le attestazioni, firmate dagli stessi, dei DPI ricevuti);', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 26, 4,'Idoneità sanitaria', 'Idoneità sanitaria con scadenza', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 27, 4,'Attestato di formazione lavoratore come previsto dall art. 37 DL 81/08 smi e accordo stato regioni vigente in materia', 'Attestato di formazione del lavoratore come previsto dall’art. 37 del D.Lgs. 81/08. Tale formazione deve essere erogata da soggetti formatori abilitati ed avere durata, indirizzi e requisiti minimi come prescritto dall’Accordo Stato Regioni vigente in materia.', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 28, 4,'Contratto', 'Tipologia di contratto', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 29, 4,'Contratto a tempo determinato', 'Se tempo determinato, inserire scadenza', '');
-- INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 30, 4,'Contratto a tempo determinato', 'Se tempo determinato, inserire scadenza', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 31, 4,'Contratto di distacco: Comunicazione impresa', 'Comunicazione formale dell impresa appaltatrice ad Enel di volersi avvalere di personale in distacco temporaneo da altra impresa, con specificazione dell impresa distaccante e delle generalità del personale distaccato;', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 32, 4,'Contratto di distacco: Dichiarazione distaccante', 'Dichiarazione dell impresa distaccante contenente l indicazione dell impresa beneficiaria del distacco, delle generalità del personale distaccato, della temporaneità del distacco e delle attività cui è destinato il personale distaccato;', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 33, 4,'Contratto di distacco: DURC', 'Certificazione che attesti la regolarità contributiva dell impresa distaccante (Durc)', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 34, 4,'Contratto di distacco: Accettazione distacco', 'Accettazione del lavoratore distaccato in merito a quanto concordato tra impresa cedente e impresa ricevente', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 35, 4,'Contratto di distacco: Copia libro matricola', 'Copia Libro Unico del Lavoro del personale distaccato', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 39, 4,'Formazione e addestarmento per l utilizzo di DPI di III categoria', 'Formazione e addestarmento per l utilizzo di DPI di III categoria', '');

-- inserimento documenti comuni anagraf. forn/contr doc mezzi
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 36, 7,'Certificato di assicurazione', 'Polizza assicurativa con quietanza di pagamento', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 37, 7,'Carta di circolazione', 'Libretto di circolazione con scadenza revizione', '');
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 38, 7,'Documentazione obbligatoria di conformità alle disposizioni dell 81/08', 'Ultimo verbale di verifica periodica in corso di validità, documentazione CE di conformità, libretti e certificati ex ISPSEL', '');
 
-- inserimento documenti comuni anagraf. forn/contr doc attrezzature
INSERT INTO "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" VALUES( 40, 8,'Attrezzature di lavoro introdotte in CTE "Speciali" ', 'Specifica documentazione attestante la conformità alle disposizioni del D.Lgs. 81/08, di mezzi trasporto e movimentazione materiali, sollevamento, piattaforme aeree, ponti mobili sviluppabili, macchine operatrici, attrezzature in genere e opere provvisionali; (dichiarazioni CE di conformità, libretti e certificati ex ISPESL, per tutti i mezzi di trasporto e sollevamento con targa, fotocopia leggibile della carta di circolazione completa, della polizza assicurativa con quietanza di pagamento, ultimo verbale di verifica periodica in corso di validità).Tutta la documentazione inerente il macchinario/attrezzatura dovrà esser a disposizione presso il cantiere.', '');