INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES_T" VALUES(1,'IT', 'DOC. AMMINISTRATIVA');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES_T" VALUES(2,'IT', 'DOC. SALUTE&SICUREZZA');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES_T" VALUES(3,'IT', 'DOC. SPECIALISTICA');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES_T" VALUES(4,'IT', 'DOC. PERSONALE ESTERNO');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES_T" VALUES(5,'IT', 'DOC. MEZZI');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES_T" VALUES(6,'IT', 'DOC. ATTREZZATURE');