INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES" VALUES(1,1, 'SUPPLIER');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES" VALUES(2,2, 'SUPPLIER');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES" VALUES(3,3, 'SUPPLIER');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES" VALUES(4,4, 'WORKER');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES" VALUES(5,1, 'CONTRACT');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES" VALUES(6,2, 'CONTRACT');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES" VALUES(7,5, 'VEHICLE');
INSERT INTO "CONTRACT_MANAGEMENT"."DOC_TYPES" VALUES(8,6, 'EQUIPMENT');