INSERT INTO "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS" VALUES(1,1);
INSERT INTO "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS" VALUES(2,2);
INSERT INTO "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS" VALUES(3,3);
INSERT INTO "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS" VALUES(4,4);