-- Protare prima la fix hotfix_plant_15_dic_2018.sql

SET SCHEMA "CONTRACT_MANAGEMENT";
------------------------------------- TABLES -------------------------------------
-- Expande column "SUBJECT" in CONTRACTS table
ALTER TABLE "CONTRACT_MANAGEMENT"."CONTRACTS" DROP (SUBJECT);
ALTER TABLE "CONTRACT_MANAGEMENT"."CONTRACTS" ADD (SUBJECT NVARCHAR(250));

-- Alter key REL_ODM_ODA_CONTRACT table
ALTER TABLE "CONTRACT_MANAGEMENT"."REL_ODM_ODA_CONTRACT" ADD (PLANT NVARCHAR(4));

ALTER TABLE "CONTRACT_MANAGEMENT"."ODM_OPERATIONS" ADD (ODM_DESCRIPTION NVARCHAR (200));
ALTER TABLE "CONTRACT_MANAGEMENT"."ODM_OPERATIONS" ADD (OPERATION_DESCRIPTION NVARCHAR (200));

-- Testi stato testata RA
CREATE COLUMN TABLE "RA_DAILY_STATES_T"(
	ID_RA_DAILY_STATE INTEGER,
	SPRAS NVARCHAR(2),
	TEXT NVARCHAR(150),
	PRIMARY KEY (
		ID_RA_DAILY_STATE,
		SPRAS
	)
);

CREATE COLUMN TABLE "RA_DAILY_ODMOP_STATES_T"(
	ID_RA_DAILY_ODMOP_STATES INTEGER,
	SPRAS NVARCHAR(2),
	TEXT NVARCHAR(150),
	PRIMARY KEY (
		RA_DAILY_ODMOP_STATES_T,
		SPRAS
	)
);

-- Tabella testata RA o annotazione
CREATE COLUMN TABLE "RA_DAILY_HEAD"(
    UUID_RA_DAILY_HEAD NVARCHAR(36),
    CS_DESCRIPTION NVARCHAR (50),
    ODA NVARCHAR(20),
    ID_CONTRACT NVARCHAR(20),
    PLANT NVARCHAR(4),
    ID_SUPPLIER NVARCHAR(50),
    DATE DATE,
    DOCUMENT_NAME NVARCHAR(100),
    ID_RA_DAILY_STATE INTEGER,
	
	SAVE_AND_SEND_BY NVARCHAR(100), ------------------------------------ UTENTE CHE HA SALVATO E INVIATO IL RA
    SAVE_AND_SEND_AT DATETIME, ------------------------------------ DATA SALVATAGGIO E INVIO DEL RA
	IS_SUPPLIER_RA NVARCHAR(1), ------------------------------------ FLAG CHE INDICA SE SI TRATTA DI UN RA O DI UN'ANNOTAZIONE
	UUID_SUPPLIER_RA_HEAD NVARCHAR(36), ------------------------------------ UUID TESTATA ORIGINALE DEL RA IN CASO DI ANNOTAZIONE
    CREATED_BY NVARCHAR(100), ------------------------------------ UTENTE CHE HA CREATO IL RA/L'ANNOTAZIONE
    CREATED_AT DATETIME, ------------------------------------ DATA CREAZIONE RA/ANNOTAZIONE
	UUID_GDL NVARCHAR(36), -------------------------------------- GDL DI RIFERIMENTO
	PRIMARY KEY (
	    UUID_RA_DAILY_HEAD
	)
);

-- Tabella posizione RA
CREATE COLUMN TABLE "RA_DAILY_DETAILS"(
    UUID_RA_DAILY_DETAIL NVARCHAR(36),
    UUID_RA_DAILY_HEAD NVARCHAR(36),
    ID_ODM NVARCHAR(20),  
    ID_ODM_OPERATION NVARCHAR(10),
    CS_DESCRIPTION NVARCHAR (50),
    ID_RA_DAILY_ODMOP_STATES INTEGER,
    TOTAL_ACCOUNTING DECIMAL(34, 5),
    CURRENCY_TOT NVARCHAR(3),
    
    CREATED_BY NVARCHAR(100), 
    CREATED_AT DATETIME,
	
	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL NVARCHAR(36), ------------------------------------ UUID DETTAGLIO ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTO UN NUOVO ODM/OP (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO

	PRIMARY KEY (
	    UUID_RA_DAILY_DETAIL
	)
);

-- Tabella allegati singola posizione RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_ATTACH"(
    UUID_RA_DAILY_DETAIL_ATTACH NVARCHAR(36),
    UUID_RA_DAILY_DETAIL NVARCHAR(36),
    
    DOCUMENTAL_FILENAME NVARCHAR(300),
    FILE_LOCATION NVARCHAR(3), --SCP / OTX
    FILENAME NVARCHAR(200),
    UPLOADED_BY NVARCHAR(100),
    UPLOADED_AT DATETIME,
	
	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_ATTACH NVARCHAR(36), ------------------------------------ UUID ALLEGATO ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTO UN NUOVO ALLEGATO (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO
	PRIMARY KEY (
	    UUID_RA_DAILY_DETAIL_ATTACH
	)
);

-- Tabella note singola posizione RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_NOTES"(
    UUID_RA_DAILY_DETAIL_NOTE NVARCHAR(36),
    UUID_RA_DAILY_DETAIL NVARCHAR(36),
    TEXT NVARCHAR (250),
    CREATED_BY NVARCHAR(100),
    CREATED_AT DATETIME,

	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_ATTACH NVARCHAR(36), ------------------------------------ UUID NOTA ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTA UNA NUOVA NOTA (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO
	
	PRIMARY KEY (
	    UUID_RA_DAILY_DETAIL_NOTE
	)
);

-- Tabella lavoratore singola posizione RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_WORKER"(
    UUID_RA_DAILY_DETAIL_WORKER NVARCHAR(36),
    UUID_RA_DAILY_DETAIL NVARCHAR(36),
    ID_WORKER NVARCHAR(50),
    TIME1_BEG DATETIME,
    TIME1_END DATETIME,
    TIME2_BEG DATETIME,
    TIME2_END DATETIME,
    TIME_BREAK DATETIME,
    TOTAL_HOURS INTEGER,
    
    CREATED_BY NVARCHAR(100),
    CREATED_AT DATETIME,
	
	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_WORKER NVARCHAR(36), ------------------------------------ UUID LAVORATORE ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTO UN NUOVO LAVORATORE (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO
	
	PRIMARY KEY (
	    UUID_RA_DAILY_DETAIL_WORKER
	)
);

-- Tabella veicoli singola posizione RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_VEHICLE"(
    UUID_RA_DAILY_DETAIL_VEHICLE NVARCHAR(36),
    UUID_RA_DAILY_DETAIL NVARCHAR(36),
    ID_VEHICLE NVARCHAR(50),
    TIME1_BEG DATETIME,
    TIME1_END DATETIME,
    TIME2_BEG DATETIME,
    TIME2_END DATETIME,
    TIME_BREAK DATETIME,
    TOTAL_HOURS INTEGER,
    
    CREATED_BY NVARCHAR(100),
    CREATED_AT DATETIME,
	
	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_VEHICLE NVARCHAR(36), ------------------------------------ UUID VEICOLO ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTO UN NUOVO VEICOLO (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO
	
	PRIMARY KEY (
	    UUID_RA_DAILY_DETAIL_VEHICLE
	)
);


-- Tabella attrezzature singola posizione RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_EQUIPMENT"(
    UUID_RA_DAILY_DETAIL_EQUIPMENT NVARCHAR(36),
    UUID_RA_DAILY_DETAIL NVARCHAR(36),
    ID_EQUIPMENT NVARCHAR(50),
    TIME1_BEG DATETIME,
    TIME1_END DATETIME,
    TIME2_BEG DATETIME,
    TIME2_END DATETIME,
    TIME_BREAK DATETIME,
    TOTAL_HOURS INTEGER,
    
    CREATED_BY NVARCHAR(100),
    CREATED_AT DATETIME,
	
	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_EQUIPMENT NVARCHAR(36), ------------------------------------ UUID ATTREZZATURA ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTO UNA NUOVA ATTREZZATURA (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO

	PRIMARY KEY (
	    UUID_RA_DAILY_DETAIL_EQUIPMENT
	)
);

-- Testi posizioni prezzo per operazione OdM
CREATE COLUMN TABLE "RA_DAILY_ODMOP_ACCOUNTING"(
	UUID_RA_DAILY_DETAIL NVARCHAR(36),
	ODA_POS NVARCHAR(10),
	ODA_POS_PRICE_ROW NVARCHAR(10),

	SHORT_DESC	NVARCHAR(50),
	LONG_DESC	NVARCHAR(200),
	QUANTITY DECIMAL(34, 5),
	UM NVARCHAR(10),	
	PRICE_FOR_UNIT DECIMAL(34, 5),
	CURRENCY NVARCHAR(3),

	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_ACCOUNTING NVARCHAR(36), ------------------------------------ UUID CONTABILITA' ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTA UNA NUOVA CONTABILITA' (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO

	PRIMARY KEY (
		UUID_RA_DAILY_DETAIL,
		ODA_POS,
		ODA_POS_PRICE_ROW
	)
);

-- Tabella allegati servizi accessori RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_ATTACH_NONCORE_SERVICES"(
    UUID_RA_DAILY_HEAD_ATTACH NVARCHAR(36),
    UUID_RA_DAILY_HEAD NVARCHAR(36),
    
    DOCUMENTAL_FILENAME NVARCHAR(300),
    FILE_LOCATION NVARCHAR(3), --SCP / OTX
    FILENAME NVARCHAR(200),
    UPLOADED_BY NVARCHAR(100),
    UPLOADED_AT DATETIME,

	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_ATTACH NVARCHAR(36), ------------------------------------ UUID ALLEGATO ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTO UN NUOVO ALLEGATO (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO
	PRIMARY KEY (
	    UUID_RA_DAILY_HEAD_ATTACH
	)
);

-- Tabella note servizi accessori RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_NOTES_NONCORE_SERVICES"(
    UUID_RA_DAILY_HEAD_NOTE NVARCHAR(36),
    UUID_RA_DAILY_HEAD NVARCHAR(36),
    TEXT NVARCHAR (250),
    CREATED_BY NVARCHAR(100),
    CREATED_AT DATETIME,
	
	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_ATTACH NVARCHAR(36), ------------------------------------ UUID NOTA ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTA UNA NUOVA NOTA (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO
	PRIMARY KEY (
	    UUID_RA_DAILY_HEAD_NOTE
	)
);

-- Tabella lavoratore servizi accessori RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_WORKER_NONCORE_SERVICES"(
    UUID_RA_DAILY_HEAD_WORKER NVARCHAR(36),
    UUID_RA_DAILY_HEAD NVARCHAR(36),
    ID_WORKER NVARCHAR(50),
    TIME1_BEG DATETIME,
    TIME1_END DATETIME,
    TIME2_BEG DATETIME,
    TIME2_END DATETIME,
    TIME_BREAK DATETIME,
    TOTAL_HOURS INTEGER,
    
    CREATED_BY NVARCHAR(100),
    CREATED_AT DATETIME,
	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	
	UUID_SUPPLIER_RA_DETAIL_WORKER NVARCHAR(36), ------------------------------------ UUID LAVORATORE ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTO UN NUOVO LAVORATORE (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO
	PRIMARY KEY (
	    UUID_RA_DAILY_HEAD_WORKER
	)
);

-- Tabella veicoli servizi accessori RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_VEHICLE_NONCORE_SERVICES"(
    UUID_RA_DAILY_HEAD_VEHICLE NVARCHAR(36),
    UUID_RA_DAILY_HEAD NVARCHAR(36),
    ID_VEHICLE NVARCHAR(50),
    TIME1_BEG DATETIME,
    TIME1_END DATETIME,
    TIME2_BEG DATETIME,
    TIME2_END DATETIME,
    TIME_BREAK DATETIME,
    TOTAL_HOURS INTEGER,
    
    CREATED_BY NVARCHAR(100),
    CREATED_AT DATETIME,
	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_VEHICLE NVARCHAR(36), ------------------------------------ UUID VEICOLO ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTO UN NUOVO VEICOLO (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO
	PRIMARY KEY (
	    UUID_RA_DAILY_HEAD_VEHICLE
	)
);


-- Tabella attrezzature servizi accessori RA
CREATE COLUMN TABLE "RA_DAILY_DETAIL_EQUIPMENT_NONCORE_SERVICES"(
    UUID_RA_DAILY_HEAD_EQUIPMENT NVARCHAR(36),
    UUID_RA_DAILY_HEAD NVARCHAR(36),
    ID_EQUIPMENT NVARCHAR(50),
    TIME1_BEG DATETIME,
    TIME1_END DATETIME,
    TIME2_BEG DATETIME,
    TIME2_END DATETIME,
    TIME_BREAK DATETIME,
    TOTAL_HOURS INTEGER,
    
    CREATED_BY NVARCHAR(100),
    CREATED_AT DATETIME,

	IS_DELETED NVARCHAR(1), ------------------------------------ FLAG CHE INDICA LA CANCELLAZIONE LOGICA IN CASO DI ANNOTAZIONE
	UUID_SUPPLIER_RA_DETAIL_EQUIPMENT NVARCHAR(36), ------------------------------------ UUID ATTREZZATURA ODM/OP ORIGINALE DEL RA IN CASO DI ANNOTAZIONE. SE VIENE AGGIUNTO UNA NUOVA ATTREZZATURA (NON PRESENTE PRECEDENTEMENTE NEL RA DEL FORNITORE) SARA' VUOTO
	
	PRIMARY KEY (
	    UUID_RA_DAILY_HEAD_EQUIPMENT
	)
);

-- Tabella testi stati GdL
CREATE COLUMN TABLE "GDL_STATUS_T"(
	    ID_GDL_STATUS_T INTEGER,
		SPRAS NVARCHAR(2),
		TEXT NVARCHAR(100),

	PRIMARY KEY (
	    ID_GDL_STATUS_T,
		SPRAS
	)
);
 
-- Tabella testi stati GdL
CREATE COLUMN TABLE "GDL_STATUS"(
	    ID_GDL_STATUS INTEGER,
		ID_GDL_STATUS_T INTEGER,
		
	PRIMARY KEY (
	    ID_GDL_STATUS
	)
);

-- Tabella GdL
CREATE COLUMN TABLE "GDL"(
    UUID_GDL NVARCHAR(36),
    ID_GDL_STATUS INTEGER,
	
    START_DATE DATE,
    END_DATE DATE,
        
    CREATED_BY NVARCHAR(100),
    CREATED_AT DATETIME,
	
	PRIMARY KEY (
	    UUID_GDL
	)
);
------------------------------------- VIEWS -------------------------------------
-- Creazione view ra daily detail
CREATE VIEW "V_RA_DAILY_DETAIL"    
AS
	SELECT DISTINCT
	    RDH."UUID_RA_DAILY_HEAD" AS "UuidRaDailyHead",
	    RDH."CS_DESCRIPTION" AS "CsDescription",
	    RDH."ODA" AS "OdA",
	    RDH."ID_CONTRACT" AS "IdContract",
	    RDH."PLANT" AS "Plant",
	    RDH."DATE" AS "Date",
	    RDH."DOCUMENT_NAME" AS "DocumentName",
	    RDH."ID_RA_DAILY_STATE" AS "IdRaDailyState",
		
	    RDH."SAVE_AND_SEND_BY" AS "SaveAndSendBy",
	    RDH."SAVE_AND_SEND_AT" AS "SaveAndSendAt",
	    RDH."IS_SUPPLIER_RA" AS "IsSupplierRa",
		RDH."UUID_SUPPLIER_RA_HEAD" AS "ExtendedUuidRaDailyHead",
	    RDH."UUID_GDL" AS "UuidGdL",
	    RDH."CREATED_BY" AS "RaHeadCreatedBy",
	    RDH."CREATED_AT" AS "RaHeadCreatedAt",
		
	    RDST."TEXT" AS "RaDailyStateDesc",
	    RDST."SPRAS" AS "RaDailyStateSpras",
	    
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CREATED_BY" AS "CreatedBy",
	    RDD."CREATED_AT" AS "CreatedAt",
	    RDD."ID_RA_DAILY_ODMOP_STATES" AS "IdOdMOperationStatus",
	    RDD."TOTAL_ACCOUNTING" AS "TotalAccounting",
	    RDD."CURRENCY_TOT" AS "TotalCurrency",
	    RDOST."TEXT" AS "OdMOperationStatusDesc",
	    RDOST."SPRAS" AS "OdMOperationStatusSpras",
	    
	    ROOC."ODM_DESCRIPTION" AS "OdMDescription",
	    ROOC."OPERATION_DESCRIPTION" AS "OdMOperationDescription"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_HEAD" as RDH
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" as RDST on RDH."ID_RA_DAILY_STATE" = RDST."ID_RA_DAILY_STATE"
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD on RDH."UUID_RA_DAILY_HEAD" = RDD."UUID_RA_DAILY_HEAD"
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" as RDOST on RDD."ID_RA_DAILY_ODMOP_STATES" = RDOST."ID_RA_DAILY_ODMOP_STATES"
		LEFT JOIN "CONTRACT_MANAGEMENT"."REL_ODM_ODA_CONTRACT" as ROOC on ROOC."ID_ODM" = RDD."ID_ODM" AND ROOC."ID_ODM_OPERATION" = RDD."ID_ODM_OPERATION";
		
-- Creazione view ra daily detail attach
CREATE VIEW "V_RA_DAILY_DETAIL_ATTACH"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDA."UUID_RA_DAILY_DETAIL_ATTACH" AS "UuidRaDailyDetailAttach",
	    RDDA."DOCUMENTAL_FILENAME" AS "DocumentalFilename",
	    RDDA."FILE_LOCATION" AS "FileLocation",
	    RDDA."FILENAME" AS "Filename",
	    RDDA."UPLOADED_BY" AS "UploadedBy",
	    RDDA."UPLOADED_AT" AS "UploadedAt",
	    RDDA."IS_DELETED" AS "IsDeleted"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_ATTACH" as RDDA on RDD."UUID_RA_DAILY_DETAIL" = RDDA."UUID_RA_DAILY_DETAIL";
		
-- Creazione view ra daily detail notes
CREATE VIEW "V_RA_DAILY_DETAIL_NOTES"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDN."UUID_RA_DAILY_DETAIL_NOTE" AS "UuidRaDailyDetailNote",
	    RDDN."TEXT" AS "Text",
	    RDDN."CREATED_BY" AS "CreatedBy",
	    RDDN."CREATED_AT" AS "CreatedAt",
		RDDN."IS_DELETED" AS "IsDeleted"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_NOTES" as RDDN on RDD."UUID_RA_DAILY_DETAIL" = RDDN."UUID_RA_DAILY_DETAIL";		
		
-- Creazione view ra daily detail workers
CREATE VIEW "V_RA_DAILY_DETAIL_WORKERS"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDW."UUID_RA_DAILY_DETAIL_WORKER" AS "UuidRaDailyDetailWorker",
	    RDDW."ID_WORKER" AS "IdWorker",
	    RDDW."TIME1_BEG" AS "Time1Beg",
	    RDDW."TIME1_END" AS "Time1End",
	    RDDW."TIME2_BEG" AS "Time2Beg",
	    RDDW."TIME2_END" AS "Time2End",
	    RDDW."TIME_BREAK" AS "TimeBreak",
	    RDDW."TOTAL_HOURS" AS "TotalHours",
	    RDDW."CREATED_AT" AS "CreatedAt",
	    RDDW."CREATED_BY" AS "CreatedBy",
		RDDW."IS_DELETED" AS "IsDeleted",

	    W."NAME" AS "name",
	    W."SURNAME" AS "surname",
	    W."CONTRACT_EXPIRED_DATE" AS "contractExpiredDate"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_WORKER" as RDDW on RDD."UUID_RA_DAILY_DETAIL" = RDDW."UUID_RA_DAILY_DETAIL"
		JOIN "CONTRACT_MANAGEMENT"."WORKERS" as W on RDDW."ID_WORKER" = W."ID_WORKER";
		
-- Creazione view ra daily detail vehicle
CREATE VIEW "V_RA_DAILY_DETAIL_VEHICLE"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDV."UUID_RA_DAILY_DETAIL_VEHICLE" AS "UuidRaDailyDetailVehicle",
	    RDDV."ID_VEHICLE" AS "IdVehicle",
	    RDDV."TIME1_BEG" AS "Time1Beg",
	    RDDV."TIME1_END" AS "Time1End",
	    RDDV."TIME2_BEG" AS "Time2Beg",
	    RDDV."TIME2_END" AS "Time2End",
	    RDDV."TIME_BREAK" AS "TimeBreak",
	    RDDV."TOTAL_HOURS" AS "TotalHours",
	    RDDV."CREATED_AT" AS "CreatedAt",
	    RDDV."CREATED_BY" AS "CreatedBy",
		RDDV."IS_DELETED" AS "IsDeleted",
		
	    V."BRAND" AS "Brand"
		
		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_VEHICLE" as RDDV on RDD."UUID_RA_DAILY_DETAIL" = RDDV."UUID_RA_DAILY_DETAIL"
		JOIN "CONTRACT_MANAGEMENT"."VEHICLES" as V on RDDV."ID_VEHICLE" = V."ID_VEHICLES";			
		
-- Creazione view ra daily detail equipment
CREATE VIEW "V_RA_DAILY_DETAIL_EQUIPMENT"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDE."UUID_RA_DAILY_DETAIL_EQUIPMENT" AS "UuidRaDailyDetailEquipment",
	    RDDE."ID_EQUIPMENT" AS "IdEquipment",
	    RDDE."TIME1_BEG" AS "Time1Beg",
	    RDDE."TIME1_END" AS "Time1End",
	    RDDE."TIME2_BEG" AS "Time2Beg",
	    RDDE."TIME2_END" AS "Time2End",
	    RDDE."TIME_BREAK" AS "TimeBreak",
	    RDDE."TOTAL_HOURS" AS "TotalHours",
	    RDDE."CREATED_AT" AS "CreatedAt",
	    RDDE."CREATED_BY" AS "CreatedBy",
		RDDE."IS_DELETED" AS "IsDeleted",
	    E."DESCRIPTION" AS "Description",
	    E."MANUFACTURER" AS "Manufacturer",
	    E."MODEL" AS "Model"
		
		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_EQUIPMENT" as RDDE on RDD."UUID_RA_DAILY_DETAIL" = RDDE."UUID_RA_DAILY_DETAIL"
		JOIN "CONTRACT_MANAGEMENT"."EQUIPMENT" as E on RDDE."ID_EQUIPMENT" = E."ID_EQUIPMENT";

-- Creazione view ra non core worker
CREATE VIEW "V_RA_DAILY_DETAIL_WORKER_NONCORE"    
AS
	SELECT DISTINCT
	    RDDWNS."UUID_RA_DAILY_HEAD_WORKER" AS "UUID_RA_DAILY_HEAD_WORKER",
	    RDDWNS."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
	    RDDWNS."ID_WORKER" AS "ID_WORKER",
	    RDDWNS."TIME1_BEG" AS "TIME1_BEG",
	    RDDWNS."TIME1_END" AS "TIME1_END",
	    RDDWNS."TIME2_BEG" AS "TIME2_BEG",
	    RDDWNS."TIME2_END" AS "TIME2_END",
	    RDDWNS."TIME_BREAK" AS "TIME_BREAK",
	    RDDWNS."CREATED_AT" AS "CREATED_AT",
	    RDDWNS."CREATED_BY" AS "CREATED_BY",
		RDDWNS."IS_DELETED" AS "IsDeleted",
		RDDWNS.TOTAL_HOURS  AS "TOTAL_HOURS", 
	    
	    W."NAME" AS "NAME",
	    W."SURNAME" AS "SURNAME"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_WORKER_NONCORE_SERVICES" as RDDWNS
		JOIN "CONTRACT_MANAGEMENT"."WORKERS" as W on RDDWNS."ID_WORKER" = W."ID_WORKER";
		
-- Creazione view ra non core vehicle
CREATE VIEW "V_RA_DAILY_DETAIL_VEHICLE_NONCORE"    
AS
	SELECT DISTINCT
	    RDDVNS."UUID_RA_DAILY_HEAD_VEHICLE" AS "UUID_RA_DAILY_HEAD_VEHICLE",
	    RDDVNS."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
	    RDDVNS."ID_VEHICLE" AS "ID_VEHICLE",
	    RDDVNS."TIME1_BEG" AS "TIME1_BEG",
	    RDDVNS."TIME1_END" AS "TIME1_END",
	    RDDVNS."TIME2_BEG" AS "TIME2_BEG",
	    RDDVNS."TIME2_END" AS "TIME2_END",
	    RDDVNS."TIME_BREAK" AS "TIME_BREAK",
	    RDDVNS."CREATED_AT" AS "CREATED_AT",
	    RDDVNS."CREATED_BY" AS "CREATED_BY",
		RDDVNS."IS_DELETED" AS "IsDeleted",
		RDDVNS.TOTAL_HOURS  AS "TOTAL_HOURS", 
	    
	    V."BRAND" AS "BRAND"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_VEHICLE_NONCORE_SERVICES" as RDDVNS
		JOIN "CONTRACT_MANAGEMENT"."VEHICLES" as V on RDDVNS."ID_VEHICLE" = V."ID_VEHICLES";

-- Creazione view ra non core equipment
CREATE VIEW "V_RA_DAILY_DETAIL_EQUIPMENT_NONCORE"    
AS
	SELECT DISTINCT
	    RDDENS."UUID_RA_DAILY_HEAD_EQUIPMENT" AS "UUID_RA_DAILY_HEAD_EQUIPMENT",
	    RDDENS."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
	    RDDENS."ID_EQUIPMENT" AS "ID_EQUIPMENT",
	    RDDENS."TIME1_BEG" AS "TIME1_BEG",
	    RDDENS."TIME1_END" AS "TIME1_END",
	    RDDENS."TIME2_BEG" AS "TIME2_BEG",
	    RDDENS."TIME2_END" AS "TIME2_END",
	    RDDENS."TIME_BREAK" AS "TIME_BREAK",
	    RDDENS."CREATED_AT" AS "CREATED_AT",
	    RDDENS."CREATED_BY" AS "CREATED_BY",
		RDDENS."IS_DELETED" AS "IsDeleted",
		RDDENS.TOTAL_HOURS  AS "TOTAL_HOURS", 
	    
	    E."DESCRIPTION" AS "DESCRIPTION"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_EQUIPMENT_NONCORE_SERVICES" as RDDENS
		JOIN "CONTRACT_MANAGEMENT"."EQUIPMENT" as E on RDDENS."ID_EQUIPMENT" = E."ID_EQUIPMENT";		
		
-- Creazione view per estrazione dati contratto relativi ad un CS (view apposita per GdL)
CREATE VIEW "V_CONTRACT_TO_CS_FOR_GDL"
AS
	SELECT DISTINCT
	
	    C."ID_CONTRACT"                       AS "IdContract",
	    C."SUBJECT"                           AS "ContractSubject",
	    C."PLANT"                             AS "Plant",
	    
		S."SUPPLIER_NAME"                     AS "SupplierName",
		S."ID_SUPPLIER"                       AS "CodFornitore",
		
		CS."NAME"                             AS "CSName",
		CS."SURNAME"                          AS "CSSurname",
		CS."ID_CONTRACT_SUPERVISORS"          AS "CSId",
		CS."IS_CS"         					  AS "CSIsCSMain",
		
		GS."ID_GREEN_SHEET"                   AS "IdGreenSheet",
		GS."MODIFIED_DOC"                     AS "GreenSheetModifiedDoc"
		
		FROM "CONTRACT_MANAGEMENT"."CONTRACTS" as C
		
		JOIN "CONTRACT_MANAGEMENT"."SUPPLIERS" as S on S."ID_UNIQUE_SUP" = C."ID_UNIQUE_SUP"
	
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATIONS" as CA on CA."ID_CONTRACT" = C."ID_CONTRACT"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATION_DETAILS" as CAD on CAD."ID_CONTRACT_ASSOCIATION" = CA."ID_CONTRACT_ASSOCIATION"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_SUPERVISORS" as CS on CS."ID_CONTRACT_SUPERVISORS" = CAD."ID_CONTRACT_SUPERVISORS"

		LEFT JOIN "CONTRACT_MANAGEMENT"."GREEN_SHEETS" as GS on C."ID_CONTRACT" = GS."ID_CONTRACT"

		WHERE CA."IS_ACTIVE_VERSION" = '1' AND (
		    GS."ID_GREEN_SHEET" IS NULL OR 
		    ( 
		        NOT GS."ID_GREEN_SHEET" IS NULL AND
		        GS."IS_ACTIVE_VERSION" = '1'AND
		        C."ID_UNIQUE_SUP" = GS."ID_UNIQUE_SUP"
		    )
 	      );		
------------------------------------- INSERT  -------------------------------------
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" VALUES(0,'IT','Nessun RA ancora compilato');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" VALUES(1,'IT','RA in bozza e non inviato');		
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" VALUES(2,'IT','RA compilato ed inviato al CS');

INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" VALUES(0,'IT','Non compilato');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" VALUES(1,'IT','Compilato');		
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" VALUES(2,'IT','Compilato e chiuso');

-- Fix estrazione plant! 
DROP VIEW "V_CONTRACT_TO_CS";
CREATE VIEW "V_CONTRACT_TO_CS"
AS
	SELECT DISTINCT
	
	    C."ID_CONTRACT"                       AS "IdContract",
	    C."PLANT"                             AS "Plant",
	    
		S."SUPPLIER_NAME"                     AS "SupplierName",
		S."ID_SUPPLIER"                       AS "CodFornitore",
		
		CS."NAME"                             AS "CSName",
		CS."SURNAME"                          AS "CSSurname",
		CS."ID_CONTRACT_SUPERVISORS"          AS "CSId"
		
		FROM "CONTRACT_MANAGEMENT"."CONTRACTS" as C
		
		JOIN "CONTRACT_MANAGEMENT"."SUPPLIERS" as S on S."ID_UNIQUE_SUP" = C."ID_UNIQUE_SUP"
	
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATIONS" as CA on CA."ID_CONTRACT" = C."ID_CONTRACT"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATION_DETAILS" as CAD on CAD."ID_CONTRACT_ASSOCIATION" = CA."ID_CONTRACT_ASSOCIATION"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_SUPERVISORS" as CS on CS."ID_CONTRACT_SUPERVISORS" = CAD."ID_CONTRACT_SUPERVISORS"
		
		WHERE CA."IS_ACTIVE_VERSION" = '1';