SET SCHEMA "CONTRACT_MANAGEMENT";

-- ALTER
-- INSERIMENTO CAMPO NELLA TABELLA DELLE REL ODM ODA CONTRACT
ALTER TABLE REL_ODM_ODA_CONTRACT ADD (SUPPLIER_NAME NVARCHAR(100));

-- VIEW
DROP VIEW "V_GDL_FOR_CALENDAR_GDL";    
CREATE VIEW "V_GDL_FOR_CALENDAR_GDL"    
AS
	SELECT DISTINCT
        GDL."UUID_GDL" AS "UUID_GDL",
        GDL."ID_GDL_STATUS" AS "ID_GDL_STATUS",
        GDL."START_DATE" AS "START_DATE",
        GDL."END_DATE" AS "END_DATE",
        GDL."CREATED_BY" AS "CREATED_BY",
        GDL."CREATED_AT" AS "CREATED_AT",
        GDL."DOCUMENT_NAME" AS "DOCUMENT_NAME",
        GDL."ID_CONTRACT" AS "ID_CONTRACT",
        GDL."ODA" AS "ODA",
        GDL."IS_SUPPLIER_VERSION" AS "IS_SUPPLIER_VERSION",
        GDL."FILENAME" AS "FILENAME",
        GDL."VERSION" AS "VERSION",
        GDL."IS_ACTIVE_VERSION" AS "IS_ACTIVE_VERSION",
        GDLST."ID_GDL_STATUS_T" as "ID_GDL_STATUS_T",
        GDLST."TEXT" as "GDL_STATUS_TEXT",
        GDLST."SPRAS" as "GDL_STATUS_SPRAS"
        
		FROM  "CONTRACT_MANAGEMENT"."GDL" as GDL
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS" as GDLS on GDL."ID_GDL_STATUS" = GDLS."ID_GDL_STATUS"		
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS_T" as GDLST on GDLS."ID_GDL_STATUS_T" = GDLST."ID_GDL_STATUS_T";
		


DROP VIEW "V_CONTRACT_TO_CS_FOR_GDL";  
CREATE VIEW "V_CONTRACT_TO_CS_FOR_GDL"
AS
	SELECT DISTINCT
	
	    C."ID_CONTRACT"                       AS "IdContract",
	    C."ID_UNIQUE_SUP"                     AS "IdUniqueSupplier",
	    C."SUBJECT"                           AS "ContractSubject",
	    C."PLANT"                             AS "Plant",
	    
		S."SUPPLIER_NAME"                     AS "SupplierName",
		S."ID_SUPPLIER"                       AS "CodFornitore",
		
		GS."ID_GREEN_SHEET"                   AS "IdGreenSheet",
		GS."MODIFIED_DOC"                     AS "GreenSheetModifiedDoc",
		
		ROOC."ODA"                            AS "Oda",
		ROOC."ODA_DESCRIPTION"                AS "OdaDescription",
		ROOC."CS_DESCRIPTION"                 AS "RelOdMOdAContractCsDescription"
		
		FROM "CONTRACT_MANAGEMENT"."CONTRACTS" as C
		
		JOIN "CONTRACT_MANAGEMENT"."SUPPLIERS" as S on S."ID_UNIQUE_SUP" = C."ID_UNIQUE_SUP"
	
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATIONS" as CA on CA."ID_CONTRACT" = C."ID_CONTRACT"
		
-- 		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATION_DETAILS" as CAD on CAD."ID_CONTRACT_ASSOCIATION" = CA."ID_CONTRACT_ASSOCIATION"
		
-- 		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_SUPERVISORS" as CS on CS."ID_CONTRACT_SUPERVISORS" = CAD."ID_CONTRACT_SUPERVISORS"

		LEFT JOIN "CONTRACT_MANAGEMENT"."GREEN_SHEETS" as GS on C."ID_CONTRACT" = GS."ID_CONTRACT"
		
		JOIN "CONTRACT_MANAGEMENT"."REL_ODM_ODA_CONTRACT" as ROOC on C."ID_CONTRACT" = ROOC."ID_CONTRACT"

		WHERE S."ID_SUPPLIER" = ROOC."SUPPLIER" AND
		    CA."IS_ACTIVE_VERSION" = '1' AND (
		    GS."ID_GREEN_SHEET" IS NULL OR 
		    ( 
		        NOT GS."ID_GREEN_SHEET" IS NULL AND
		        GS."IS_ACTIVE_VERSION" = '1'AND
		        C."ID_UNIQUE_SUP" = GS."ID_UNIQUE_SUP"
		    )
 	      );	