SET SCHEMA "CONTRACT_MANAGEMENT";

---------------ALTER
ALTER TABLE RA_DAILY_HEAD ADD (ID_APPROVAL_STATUS INTEGER);
ALTER TABLE RA_DAILY_HEAD ADD (APPROVAL_NOTE NVARCHAR(100));
ALTER TABLE RA_DAILY_DETAILS ADD (ACCEPT_NOTE NVARCHAR(500));
ALTER TABLE RA_DAILY_ODMOP_ACCOUNTING ALTER (ODA_POS_PRICE_ROW NVARCHAR(36));
---------------TABLES
CREATE COLUMN TABLE "APPROVAL_STATUS_T"(
	ID_APPROVAL_STATUS_T INTEGER,
	SPRAS NVARCHAR(2),
	TEXT NVARCHAR(50),
	PRIMARY KEY (
		ID_APPROVAL_STATUS_T,
		SPRAS
	)
);
CREATE COLUMN TABLE "APPROVAL_STATUS"(
	ID_APPROVAL_STATUS INTEGER,
	ID_APPROVAL_STATUS_T INTEGER,
	PRIMARY KEY (
		ID_APPROVAL_STATUS
	)
);

-- Tabella voci a consuntivo commons
CREATE COLUMN TABLE "RA_ACCOUNTING_CONS_COMMON"(
	ID_RA_ACCOUNTING_CONS_COMMON NVARCHAR(10),

	SHORT_DESC	NVARCHAR(50),
	LONG_DESC	NVARCHAR(200),
	QUANTITY DECIMAL(34, 5),
	UM NVARCHAR(10),	
	PRICE_FOR_UNIT DECIMAL(34, 5),
	CURRENCY NVARCHAR(3),

	IS_DELETED NVARCHAR(1), 

	PRIMARY KEY (
		ID_RA_ACCOUNTING_CONS_COMMON
	)
);

CREATE COLUMN TABLE "RA_ACCOUNTING_UM"(
	UM NVARCHAR(3),
	DESCRIPTION NVARCHAR(20),
	PRIMARY KEY (
		UM
	)
);
---------------VIEWS
CREATE VIEW "V_CONTRACT_TO_CS_FOR_GDL_SUPPLIER_SIDE"
AS
	SELECT DISTINCT
	
	    C."ID_CONTRACT"                       AS "IdContract",
	    C."SUBJECT"                           AS "ContractSubject",
	    C."PLANT"                             AS "Plant",
	    
		S."SUPPLIER_NAME"                     AS "SupplierName",
		S."ID_SUPPLIER"                       AS "CodFornitore",
		
		CS."NAME"                             AS "CSName",
		CS."SURNAME"                          AS "CSSurname",
		CS."ID_CONTRACT_SUPERVISORS"          AS "CSId",
		CAD."IS_CS_MAIN"   					  AS "CSIsCSMain",
		
		GS."ID_GREEN_SHEET"                   AS "IdGreenSheet",
		GS."MODIFIED_DOC"                     AS "GreenSheetModifiedDoc",
		
		ROOC."ODA"                            AS "Oda",
		ROOC."ODA_DESCRIPTION"                AS "OdaDescription",
		ROOC."CS_DESCRIPTION"                 AS "RelOdMOdAContractCsDescription",
		
		RDH."IS_SUPPLIER_RA"                  AS "IsSupplierRa",
		RDH."UUID_RA_DAILY_HEAD"              AS "UuidRaDailyHead",
		RDH."ID_APPROVAL_STATUS"              AS "IdApprovalStatus",
		RDH."APPROVAL_NOTE"                   AS "ApprovalNote",
		
		GDL."UUID_GDL"                        AS "IdGdL",
		GDL."ID_GDL_STATUS"                   AS "IdGdLStatus",
		GDL."IS_SUPPLIER_VERSION"             AS "IsGdLSupplierVersion",
		GDL."IS_ACTIVE_VERSION"               AS "IsGdLActiveVersion"
		
		FROM "CONTRACT_MANAGEMENT"."CONTRACTS" as C
		JOIN "CONTRACT_MANAGEMENT"."SUPPLIERS" as S on S."ID_UNIQUE_SUP" = C."ID_UNIQUE_SUP"
		
		JOIN "CONTRACT_MANAGEMENT"."REL_ODM_ODA_CONTRACT" as ROOC on C."ID_CONTRACT" = ROOC."ID_CONTRACT" AND ROOC."SUPPLIER" = S."ID_SUPPLIER"
		JOIN "CONTRACT_MANAGEMENT"."GDL" as GDL on GDL."ID_CONTRACT" = ROOC."ID_CONTRACT" AND GDL."ODA" = ROOC."ODA"
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_HEAD" as RDH on RDH."UUID_GDL" = GDL."UUID_GDL"
		
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATIONS" as CA on CA."ID_CONTRACT" = C."ID_CONTRACT"
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATION_DETAILS" as CAD on CAD."ID_CONTRACT_ASSOCIATION" = CA."ID_CONTRACT_ASSOCIATION"
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_SUPERVISORS" as CS on CS."ID_CONTRACT_SUPERVISORS" = CAD."ID_CONTRACT_SUPERVISORS"
		LEFT JOIN "CONTRACT_MANAGEMENT"."GREEN_SHEETS" as GS on C."ID_CONTRACT" = GS."ID_CONTRACT"
		

		WHERE CA."IS_ACTIVE_VERSION" = '1' AND (
		    GS."ID_GREEN_SHEET" IS NULL OR 
		    ( 
		        NOT GS."ID_GREEN_SHEET" IS NULL AND
		        GS."IS_ACTIVE_VERSION" = '1'AND
		        C."ID_UNIQUE_SUP" = GS."ID_UNIQUE_SUP"
		    )
 	      );
 	      
 	      
DROP VIEW V_REL_GROUP_SUPERVISORS;
CREATE VIEW "V_REL_GROUP_SUPERVISORS" 
AS
SELECT DISTINCT
	    G."PLANT"                     AS "Plant",
	  
	    CS."ID_CONTRACT_SUPERVISORS"    AS "ID_CONTRACT_SUPERVISORS",
	    CS."NAME"                       AS "NAME",
	    CS."SURNAME"                    AS "SURNAME",
	    CS."IS_CS"                      AS "IS_CS",
	    CS."IS_ASSISTANT_CS_SIC"        AS "IS_ASSISTANT_CS_SIC",
	    CS."IS_ASSISTANT_CS_AMM"        AS "IS_ASSISTANT_CS_AMM",
	    CS."IS_ASSISTANT_CS_MAN"        AS "IS_ASSISTANT_CS_MAN",
	    
	    RGC."ID_GROUP"                    AS "IdGroup",
	    G."NAME"                         AS "GroupName",
	    G."DESCRIPTION"                   AS "GroupDescription",
	    G."WORK_CENTER"                   AS "WorkerCenter",
	    
	    RGC.IS_TEAM_LEADER              AS "TeamLeader"
	    
		FROM "CONTRACT_MANAGEMENT"."GROUPS" as G
		JOIN "CONTRACT_MANAGEMENT"."REL_GROUPS_CS" as RGC on RGC."ID_GROUP" = G."ID_GROUP"
		JOIN "CONTRACT_MANAGEMENT"."CONTRACT_SUPERVISORS" as CS on CS."ID_CONTRACT_SUPERVISORS" = RGC."ID_CS";

/* Relatione per estrazione iniziale App GdL lato fornitore */
DROP VIEW "V_REL_CONTRACT_SUPERVISORS_FOR_MANAGE_GDL";
CREATE VIEW "V_REL_CONTRACT_SUPERVISORS_FOR_MANAGE_GDL" 
AS
	SELECT DISTINCT
	    RUA."ID_UB"                     AS "IdUb",
	    RUA."UB_DESC"                   AS "UbDesc",
	    RUA."AFNAM"                     AS "Afnam",
	    RUA."AFNAM_DESC"                AS "AfnamDesc",
	    RUA."PLANT"                     AS "Plant",
	    RUA."PLANT_DESC"                AS "PLANTDESC",
	    
	    CS."ID_CONTRACT_SUPERVISORS" AS "ID_CONTRACT_SUPERVISORS",
	    CS."NAME" AS "NAME",
	    CS."SURNAME" AS "SURNAME",
	    CS."EMAIL" AS "EMAIL",
	    CS."IS_CS" AS "IS_CS",
	    CS."IS_ASSISTANT_CS_SIC" AS "IS_ASSISTANT_CS_SIC",
	    CS."IS_ASSISTANT_CS_AMM" AS "IS_ASSISTANT_CS_AMM",
	    CS."IS_ASSISTANT_CS_MAN" AS "IS_ASSISTANT_CS_MAN"
	    
	    
		FROM "CONTRACT_MANAGEMENT"."REL_UB_TO_AFNAM" as RUA
		
		JOIN "CONTRACT_MANAGEMENT"."REL_USER_UB" as RUU on RUU."ID_UB" = RUA."ID_UB"
		
		JOIN "CONTRACT_MANAGEMENT"."CONTRACT_SUPERVISORS" as CS on CS."ID_CONTRACT_SUPERVISORS" = RUU."USERMANE"
		WHERE  CS."IS_CS" = 1;
		
		
DROP VIEW "V_GDL_FOR_CALENDAR_GDL" ;
CREATE VIEW "V_GDL_FOR_CALENDAR_GDL"    
AS
	SELECT DISTINCT
        GDL."UUID_GDL" AS "UUID_GDL",
        GDL."ID_GDL_STATUS" AS "ID_GDL_STATUS",
        GDL."START_DATE" AS "START_DATE",
        GDL."END_DATE" AS "END_DATE",
        GDL."CREATED_BY" AS "CREATED_BY",
        GDL."CREATED_AT" AS "CREATED_AT",
        GDL."DOCUMENT_NAME" AS "DOCUMENT_NAME",
        GDL."ID_CONTRACT" AS "ID_CONTRACT",
        GDL."ODA" AS "ODA",
        GDL."IS_SUPPLIER_VERSION" AS "IS_SUPPLIER_VERSION",
        GDL."FILENAME" AS "FILENAME",
        GDL."VERSION" AS "VERSION",
        GDL."IS_ACTIVE_VERSION" AS "IS_ACTIVE_VERSION",
        GDLST."ID_GDL_STATUS_T" as "ID_GDL_STATUS_T",
        GDLST."TEXT" as "GDL_STATUS_TEXT",
        GDLST."SPRAS" as "GDL_STATUS_SPRAS"
        
		FROM  "CONTRACT_MANAGEMENT"."GDL" as GDL
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS" as GDLS on GDL."ID_GDL_STATUS" = GDLS."ID_GDL_STATUS"		
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS_T" as GDLST on GDLS."ID_GDL_STATUS_T" = GDLST."ID_GDL_STATUS_T"
		WHERE GDL."IS_ACTIVE_VERSION" = '1';	
		
CREATE VIEW "V_REL_ODMOPERATIONS_OF_GDL_ANNOTATIONS" 
AS
	SELECT DISTINCT
	    GDL."UUID_GDL"                  AS "UuidGdL",
	    GDL."DOCUMENT_NAME"             AS "GdLName",
	    GDL."ID_GDL_STATUS"             AS "GdLStatusId",
	    GDL."FILENAME"                  AS "GdLRepositoryFilename",
		
	    GST."TEXT"             			AS "GdLStatusText",
	    GST."SPRAS"            			AS "GdLStatusSpras",
		
	    RDH."UUID_RA_DAILY_HEAD"        AS "UuidRaDailyHead",
	    RDH."DATE"                      AS "OperationDate",
	    
	    RDD."UUID_RA_DAILY_DETAIL"      AS "UuidOdmOperation",
	    RDD."ID_ODM" 					AS "Odm",
	    RDD."ID_ODM_OPERATION" 			AS "OdmOperation",
	    RDD."ACCEPT_NOTE" 			    AS "OdmOperationAcceptNote",
	    OO."ODM_DESCRIPTION"            AS "OdmDesc",
	    OO."OPERATION_DESCRIPTION"      AS "OdmOperationDesc",
	    
	    RDD."ID_RA_DAILY_ODMOP_STATES"  AS "IdOdMOperationStatus",
		
		RDOST."TEXT" 					AS "OdMOperationStatusDesc",
	    RDOST."SPRAS" 					AS "OdMOperationStatusSpras"
	    
		FROM "CONTRACT_MANAGEMENT"."GDL" as GDL
		
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_HEAD" as RDH on RDH."UUID_GDL" = GDL."UUID_GDL"
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD on RDD."UUID_RA_DAILY_HEAD" = RDH."UUID_RA_DAILY_HEAD"
		JOIN "CONTRACT_MANAGEMENT"."ODM_OPERATIONS" as OO on OO."ID_ODM_OPERATION" = RDD."ID_ODM_OPERATION" AND OO."ID_ODM" = RDD."ID_ODM"
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" as RDOST on RDD."ID_RA_DAILY_ODMOP_STATES" = RDOST."ID_RA_DAILY_ODMOP_STATES"
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS" as GS on GDL."ID_GDL_STATUS" = GS."ID_GDL_STATUS"
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS_T" as GST on GDL."ID_GDL_STATUS" = GST."ID_GDL_STATUS_T"
		WHERE GDL."IS_ACTIVE_VERSION" = '1';

CREATE VIEW "V_RA_DAILY_HEAD_FOR_CALENDAR_GDL_SUPPLIER_SIDE"    
AS
	SELECT DISTINCT
        RDH."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
        RDH."CS_DESCRIPTION" AS "CS_DESCRIPTION",
        RDH."ODA" AS "ODA",
        RDH."ID_CONTRACT" AS "ID_CONTRACT", 
        RDH."PLANT" AS "PLANT",
        RDH."ID_SUPPLIER" AS "ID_SUPPLIER",
        RDH."DATE" AS "DATE",
        RDH."DOCUMENT_NAME" AS "DOCUMENT_NAME",
        RDH."ID_RA_DAILY_STATE" AS "ID_RA_DAILY_STATE",
        RDH."SAVE_AND_SEND_BY" AS "SAVE_AND_SEND_BY",
        RDH."SAVE_AND_SEND_AT" AS "SAVE_AND_SEND_AT",
        RDH."IS_SUPPLIER_RA" AS "IS_SUPPLIER_RA",
        RDH."UUID_SUPPLIER_RA_HEAD" AS "UUID_SUPPLIER_RA_HEAD",
        RDH."CREATED_BY" AS "CREATED_BY",
        RDH."CREATED_AT" AS "CREATED_AT",
        RDH."UUID_GDL" AS "UUID_GDL",
        RDH."ID_APPROVAL_STATUS" AS "ID_APPROVAL_STATUS_RA",
        
        GDL."CREATED_BY" as "GDL_CREATED_BY",
        GDL."CREATED_AT" as "GDL_CREATED_AT",
        GDL."DOCUMENT_NAME" as "GDL_DOCUMENT_NAME",
        GDL."START_DATE" as "GDL_START_DATE",
        GDL."END_DATE" as "GDL_END_DATE",
        GDL."IS_SUPPLIER_VERSION" as "GDL_IS_SUPPLIER_VERSION",
        GDL."VERSION" as "GDL_VERSION",
        GDL."IS_ACTIVE_VERSION" as "GDL_IS_ACTIVE_VERSION",
        GDL."ID_GDL_STATUS" as "ID_GDL_STATUS",
		GDL."FILENAME" as "FILENAME",
		
        GDLST."ID_GDL_STATUS_T" as "ID_GDL_STATUS_T",
		
        GDLST."TEXT" as "GDL_STATUS_TEXT",
        GDLST."SPRAS" as "GDL_STATUS_SPRAS"
        
		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_HEAD" as RDH
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL" as GDL on RDH."UUID_GDL" = GDL."UUID_GDL"
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS" as GDLS on GDL."ID_GDL_STATUS" = GDLS."ID_GDL_STATUS"		
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS_T" as GDLST on GDLS."ID_GDL_STATUS_T" = GDLST."ID_GDL_STATUS_T";
		
		
DROP VIEW "V_RA_DAILY_HEAD_FOR_CALENDAR_GDL"; 
CREATE VIEW "V_RA_DAILY_HEAD_FOR_CALENDAR_GDL"    
AS
	SELECT DISTINCT
        RDH."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
        RDH."CS_DESCRIPTION" AS "CS_DESCRIPTION",
        RDH."ODA" AS "ODA",
        RDH."ID_CONTRACT" AS "ID_CONTRACT",
        RDH."PLANT" AS "PLANT",
        RDH."ID_SUPPLIER" AS "ID_SUPPLIER",
        RDH."DATE" AS "DATE",
        RDH."DOCUMENT_NAME" AS "DOCUMENT_NAME",
        RDH."ID_RA_DAILY_STATE" AS "ID_RA_DAILY_STATE",
        RDH."SAVE_AND_SEND_BY" AS "SAVE_AND_SEND_BY",
        RDH."SAVE_AND_SEND_AT" AS "SAVE_AND_SEND_AT",
        RDH."IS_SUPPLIER_RA" AS "IS_SUPPLIER_RA",
        RDH."UUID_SUPPLIER_RA_HEAD" AS "UUID_SUPPLIER_RA_HEAD",
        RDH."CREATED_BY" AS "CREATED_BY",
        RDH."CREATED_AT" AS "CREATED_AT",
        RDH."UUID_GDL" AS "UUID_GDL",
        
        GDL."CREATED_BY" as "GDL_CREATED_BY",
        GDL."CREATED_AT" as "GDL_CREATED_AT",
        GDL."DOCUMENT_NAME" as "GDL_DOCUMENT_NAME",
        GDL."ID_GDL_STATUS" as "ID_GDL_STATUS",
        GDL."FILENAME" as "FILENAME",
        
        GDLST."ID_GDL_STATUS_T" as "ID_GDL_STATUS_T",
        GDLST."TEXT" as "GDL_STATUS_TEXT",
        GDLST."SPRAS" as "GDL_STATUS_SPRAS"
        
		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_HEAD" as RDH
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL" as GDL on RDH."UUID_GDL" = GDL."UUID_GDL"
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS" as GDLS on GDL."ID_GDL_STATUS" = GDLS."ID_GDL_STATUS"		
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS_T" as GDLST on GDLS."ID_GDL_STATUS_T" = GDLST."ID_GDL_STATUS_T"
		WHERE GDL."IS_ACTIVE_VERSION" = '1' 
		OR (RDH."UUID_GDL" IS NULL OR RDH."UUID_GDL" = '');
		
DROP VIEW "V_RA_DAILY_DETAIL" ;
CREATE VIEW "V_RA_DAILY_DETAIL"    
AS
	SELECT DISTINCT
	    RDH."UUID_RA_DAILY_HEAD" AS "UuidRaDailyHead",
	    RDH."CS_DESCRIPTION" AS "CsDescription",
	    RDH."ODA" AS "OdA",
	    RDH."ID_CONTRACT" AS "IdContract",
	    RDH."PLANT" AS "Plant",
	    RDH."DATE" AS "Date",
	    RDH."DOCUMENT_NAME" AS "DocumentName",
	    RDH."ID_RA_DAILY_STATE" AS "IdRaDailyState",
		
	    RDH."SAVE_AND_SEND_BY" AS "SaveAndSendBy",
	    RDH."SAVE_AND_SEND_AT" AS "SaveAndSendAt",
	    RDH."IS_SUPPLIER_RA" AS "IsSupplierRa",
		RDH."UUID_SUPPLIER_RA_HEAD" AS "ExtendedUuidRaDailyHead",
	    RDH."UUID_GDL" AS "UuidGdL",
	    RDH."CREATED_BY" AS "RaHeadCreatedBy",
	    RDH."CREATED_AT" AS "RaHeadCreatedAt",
		
	    RDST."TEXT" AS "RaDailyStateDesc",
	    RDST."SPRAS" AS "RaDailyStateSpras",
	    
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."UUID_SUPPLIER_RA_DETAIL" AS "ExtendedUuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CREATED_BY" AS "CreatedBy",
	    RDD."CREATED_AT" AS "CreatedAt",
	    RDD."ID_RA_DAILY_ODMOP_STATES" AS "IdOdMOperationStatus",
	    RDD."TOTAL_ACCOUNTING" AS "TotalAccounting",
	    RDD."CURRENCY_TOT" AS "TotalCurrency",
	    RDD."ACCEPT_NOTE" AS "AcceptNote",
	    RDOST."TEXT" AS "OdMOperationStatusDesc",
	    RDOST."SPRAS" AS "OdMOperationStatusSpras",
	    
	    ROOC."ODM_DESCRIPTION" AS "OdMDescription",
	    ROOC."OPERATION_DESCRIPTION" AS "OdMOperationDescription"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_HEAD" as RDH
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" as RDST on RDH."ID_RA_DAILY_STATE" = RDST."ID_RA_DAILY_STATE"
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD on RDH."UUID_RA_DAILY_HEAD" = RDD."UUID_RA_DAILY_HEAD"
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" as RDOST on RDD."ID_RA_DAILY_ODMOP_STATES" = RDOST."ID_RA_DAILY_ODMOP_STATES"
		LEFT JOIN "CONTRACT_MANAGEMENT"."REL_ODM_ODA_CONTRACT" as ROOC on ROOC."ID_ODM" = RDD."ID_ODM" AND ROOC."ID_ODM_OPERATION" = RDD."ID_ODM_OPERATION";
		
-- Creazione view per estrazione dati contratto relativi ad un CS (view apposita per GdL)
DROP VIEW "V_CONTRACT_TO_CS_FOR_GDL";
CREATE VIEW "V_CONTRACT_TO_CS_FOR_GDL"
AS
	SELECT DISTINCT
	
	    C."ID_CONTRACT"                       AS "IdContract",
	    C."ID_UNIQUE_SUP"                     AS "IdUniqueSupplier",
	    C."SUBJECT"                           AS "ContractSubject",
	    C."PLANT"                             AS "Plant",
	    
		S."SUPPLIER_NAME"                     AS "SupplierName",
		S."ID_SUPPLIER"                       AS "CodFornitore",
		
-- 		CS."NAME"                             AS "CSName",
-- 		CS."SURNAME"                          AS "CSSurname",
-- 		CS."ID_CONTRACT_SUPERVISORS"          AS "CSId",
-- 		CS."IS_CS"         					  AS "CSIsCSMain",
		
		GS."ID_GREEN_SHEET"                   AS "IdGreenSheet",
		GS."MODIFIED_DOC"                     AS "GreenSheetModifiedDoc",
		
		ROOC."ODA"                            AS "Oda",
		ROOC."ODA_DESCRIPTION"                AS "OdaDescription",
		ROOC."CS_DESCRIPTION"                 AS "RelOdMOdAContractCsDescription"
		
		FROM "CONTRACT_MANAGEMENT"."CONTRACTS" as C
		
		JOIN "CONTRACT_MANAGEMENT"."SUPPLIERS" as S on S."ID_UNIQUE_SUP" = C."ID_UNIQUE_SUP"
	
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATIONS" as CA on CA."ID_CONTRACT" = C."ID_CONTRACT"
		
-- 		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATION_DETAILS" as CAD on CAD."ID_CONTRACT_ASSOCIATION" = CA."ID_CONTRACT_ASSOCIATION"
		
-- 		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_SUPERVISORS" as CS on CS."ID_CONTRACT_SUPERVISORS" = CAD."ID_CONTRACT_SUPERVISORS"

		LEFT JOIN "CONTRACT_MANAGEMENT"."GREEN_SHEETS" as GS on C."ID_CONTRACT" = GS."ID_CONTRACT"
		
		JOIN "CONTRACT_MANAGEMENT"."REL_ODM_ODA_CONTRACT" as ROOC on C."ID_CONTRACT" = ROOC."ID_CONTRACT"

		WHERE CA."IS_ACTIVE_VERSION" = '1' AND (
		    GS."ID_GREEN_SHEET" IS NULL OR 
		    ( 
		        NOT GS."ID_GREEN_SHEET" IS NULL AND
		        GS."IS_ACTIVE_VERSION" = '1'AND
		        C."ID_UNIQUE_SUP" = GS."ID_UNIQUE_SUP"
		    )
 	      );	
----------------------- INSERTS
INSERT INTO "CONTRACT_MANAGEMENT"."APPROVAL_STATUS" VALUES(1,1);
INSERT INTO "CONTRACT_MANAGEMENT"."APPROVAL_STATUS" VALUES(2,2);

INSERT INTO "CONTRACT_MANAGEMENT"."APPROVAL_STATUS_T" VALUES(1,'IT', 'Accettato');
INSERT INTO "CONTRACT_MANAGEMENT"."APPROVAL_STATUS_T" VALUES(2,'IT', 'Accettato con riserva');

INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" VALUES(3,'IT','Accettato');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" VALUES(4,'IT','Accettato con riserva');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" VALUES(5,'IT','Bozza copiata da RA');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" VALUES(6,'IT','Compilato');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" VALUES(7,'IT','Bozza');

INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_CONS_COMMON" VALUES(1,'Fornitura di materiali a seguito fattura','',null,null,null,'EUR', '');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_CONS_COMMON" VALUES(2,'Noleggi a caldo di attrezzature','',null,null,null,'EUR', '');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_CONS_COMMON" VALUES(3,'Noleggi a caldo di macchine','',null,null,null,'EUR', '');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_CONS_COMMON" VALUES(4,'Noleggi a freddo di attrezzature','',null,null,null,'EUR', '');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_CONS_COMMON" VALUES(5,'Noleggio a freddo di macchinari','',null,null,null,'EUR', '');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_CONS_COMMON" VALUES(6,'Prestazioni di manodopera','',null,null,null,'EUR', '');

INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('G.','Giorni');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('H','Ora');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('KG','Chilogrammo');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('L','Litri');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('M','Metro');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('M2','Metro quadro');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('M3','Metro cubo');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('NUM','Numero');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('Q','Quintale');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_ACCOUNTING_UM" VALUES('T','Tonnellata');

