SET SCHEMA "CONTRACT_MANAGEMENT";
--- ATTENZIONE. PER MODIFICARE DELLE PRIMARY KEY VERRÀ CANCELLATA IL CONTENUTO DELLA TABELLA GDL
-- Modifiche DB Contract Management - Ass Contratto già salite in test (messe cmq nello script per quando ci sarà il trasporto in produzione)
ALTER TABLE WORKERS ADD (CREATED_BY NVARCHAR(20));
ALTER TABLE WORKERS ADD (CREATED_DATE TIMESTAMP);
ALTER TABLE VEHICLES ADD (CREATED_BY NVARCHAR(20));
ALTER TABLE VEHICLES ADD (CREATED_DATE TIMESTAMP);
ALTER TABLE EQUIPMENT ADD (CREATED_BY NVARCHAR(20));
ALTER TABLE EQUIPMENT ADD (CREATED_DATE TIMESTAMP);

ALTER TABLE WORKERS ADD (CHANGED_BY NVARCHAR(20));
ALTER TABLE WORKERS ADD (CHANGED_DATE TIMESTAMP);
ALTER TABLE VEHICLES ADD (CHANGED_BY NVARCHAR(20));
ALTER TABLE VEHICLES ADD (CHANGED_DATE TIMESTAMP);
ALTER TABLE EQUIPMENT ADD (CHANGED_BY NVARCHAR(20));
ALTER TABLE EQUIPMENT ADD (CHANGED_DATE TIMESTAMP);

ALTER TABLE REL_CONTRACT_WORKER ADD (APPROVAL_DATE TIMESTAMP);
ALTER TABLE REL_CONTRACT_WORKER ADD (APPROVAL_DATE TIMESTAMP); 
ALTER TABLE REL_CONTRACT_WORKER ADD (APPROVAL_USER NVARCHAR(20));
ALTER TABLE REL_CONTRACT_EQUIPMENT ADD (APPROVAL_DATE TIMESTAMP); 
ALTER TABLE REL_CONTRACT_EQUIPMENT ADD (APPROVAL_USER NVARCHAR(20));
ALTER TABLE REL_CONTRACT_VEHICLE ADD (APPROVAL_DATE TIMESTAMP); 
ALTER TABLE REL_CONTRACT_VEHICLE ADD (APPROVAL_USER NVARCHAR(20));
ALTER TABLE REL_ODM_ODA_CONTRACT ADD (ASSIGMENT_DATE DATE);

INSERT INTO VEHICLES_TYPES VALUES(0, 0);
UPDATE VEHICLES_TYPES_T SET TEXT = 'N/A' WHERE ID_VEHICLES_TYPES_T=0;

INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" VALUES(3,'IT','Annotazione non compilata');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" VALUES(4,'IT','Annotazione in bozza');		
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" VALUES(5,'IT','Annotazione pronta per invio al GdL');
INSERT INTO "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" VALUES(6,'IT','Annotazione inserita in un GdL');

ALTER TABLE "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_NOTES" DROP (UUID_SUPPLIER_RA_DETAIL_ATTACH);
ALTER TABLE "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_NOTES" ADD (UUID_SUPPLIER_RA_DETAIL_NOTE NVARCHAR(36));

ALTER TABLE "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_NOTES_NONCORE_SERVICES" DROP (UUID_SUPPLIER_RA_DETAIL_ATTACH);
ALTER TABLE "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_NOTES_NONCORE_SERVICES" ADD (UUID_SUPPLIER_RA_DETAIL_NOTE NVARCHAR(36));

DELETE FROM "CONTRACT_MANAGEMENT"."GDL";
ALTER TABLE "CONTRACT_MANAGEMENT"."GDL" ADD (IS_ACTIVE_VERSION NVARCHAR(1));
ALTER TABLE "CONTRACT_MANAGEMENT"."GDL" ADD (DOCUMENT_NAME NVARCHAR(100));
ALTER TABLE "CONTRACT_MANAGEMENT"."GDL" ADD (ID_CONTRACT NVARCHAR(20));
ALTER TABLE "CONTRACT_MANAGEMENT"."GDL" ADD (ODA NVARCHAR(20));
ALTER TABLE "CONTRACT_MANAGEMENT"."GDL" ADD (IS_SUPPLIER_VERSION NVARCHAR(1));
ALTER TABLE "CONTRACT_MANAGEMENT"."GDL" ADD (FILENAME NVARCHAR(100));
ALTER TABLE "CONTRACT_MANAGEMENT"."GDL" ADD (VERSION INTEGER);
ALTER TABLE "CONTRACT_MANAGEMENT"."GDL" DROP PRIMARY KEY;
ALTER TABLE "CONTRACT_MANAGEMENT"."GDL" ADD PRIMARY KEY (UUID_GDL, VERSION); 


INSERT INTO "CONTRACT_MANAGEMENT"."GDL_STATUS" VALUES(1,1);
INSERT INTO "CONTRACT_MANAGEMENT"."GDL_STATUS_T" VALUES(1,'IT','Inviato al fornitore ma non ancora accettato');
INSERT INTO "CONTRACT_MANAGEMENT"."GDL_STATUS" VALUES(2,2);
INSERT INTO "CONTRACT_MANAGEMENT"."GDL_STATUS_T" VALUES(2,'IT','Inviato al fornitore e accettato con riserva');
INSERT INTO "CONTRACT_MANAGEMENT"."GDL_STATUS" VALUES(3,3);
INSERT INTO "CONTRACT_MANAGEMENT"."GDL_STATUS_T" VALUES(3,'IT','Inviato al fornitore e accettato senza riserva');

-- ATTENZIONE!!!!!!!!!!!!!!!!!!! Aggiornare l'xsodata con la nuova tabella e fare le insert manualmente
CREATE COLUMN TABLE "REL_PLANT_COMMON_DOC2"(
	ID_COMMON_DOCUMENTS INTEGER,
	PLANT NVARCHAR(4),
	PRIMARY KEY (
		ID_COMMON_DOCUMENTS,
		PLANT
	)
);

/* Modifica V_REL_SUPPLIER_WORKER */
/* Relatione tra SUPPLIER e WORKER */
DROP VIEW V_REL_SUPPLIER_WORKER;
CREATE VIEW "V_REL_SUPPLIER_WORKER" 
AS
	SELECT DISTINCT
	    W."ID_WORKER"                   AS "IdWorker",
	    W."NAME"                        AS "WorkerName",
	    W."SURNAME"                     AS "WorkerSurname",
	    W."DATE_BIRTH"                  AS "WorkerDateBirth",
	    W."GENDER"                      AS "WorkerGender",
	    W."RESIDENCE"                   AS "WorkerResidence",
	    W."CONTRACT_EXPIRED_DATE"       AS "WorkerContractExpiredDate",
	    W."CUSTOM_ROLES"                AS "WorkerCustomRoles",
	    W."CUSTOM_QUALIFICATIONS"       AS "WorkerCustomQualifications",
	    W."EU_CITIZEN"                  AS "WorkerCitizenship",
        W."DPI_III_LEVEL"               AS "WorkerDpiIIILevel",
        W."CREATED_BY"                  AS "WorkerCreatedBy",
        W."CHANGED_BY"                  AS "WorkerChangedBy",
        W."CREATED_DATE"                AS "WorkerCreatedDate",
        W."CHANGED_DATE"                AS "WorkerChangedDate",
	    
	    WCT."ID_WORKER_CONTRACT_TYPE"    as "IdWorkerContractType",
	    WCTT."TEXT"                      as "WorkerContractTypeText",
	    WCTT."SPRAS"                     as "WorkerContractTypeSpras",
	    RSW."ID_UNIQUE_SUP"              as "IdSupplier",
	    RSW."VALIDATED_BY"               as "WorkerValidatedBy",
	    RSW."STATUS"                     as "WorkerStatus",
	    ATST."TEXT"                      as "WorkerStatusText",     
	    S."SUPPLIER_NAME"                as "SupplierName",
	    MIN(A."EXPIRED_DATE")            as "minAttachmentExpiredDate"
		FROM "CONTRACT_MANAGEMENT"."WORKERS" as W
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."DOCUMENTS" as D on D."ID_WORKER" = W."ID_WORKER"
		LEFT JOIN "CONTRACT_MANAGEMENT"."DOC_TYPES" as DT on DT."ID_DOC_TYPES" = D."ID_DOC_TYPE"
	    LEFT JOIN "CONTRACT_MANAGEMENT"."DOC_TYPES_T" as DTT on DTT."ID_DOC_TYPES_T" = DT."ID_DOC_TYPES_T"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."ATTACHMENTS" as A on A."ID_DOCUMENT" = D."ID_DOCUMENT"
		LEFT JOIN "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS" as AST on AST."ID_ATTACHMENT_STATUS" = A."ID_ATTACHMENT_STATUS"
		LEFT JOIN "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS_T" as ASTT on ASTT."ID_ATTACHMENT_STATUS_T" = AST."ID_ATTACHMENT_STATUS_T"
			
		LEFT JOIN "CONTRACT_MANAGEMENT"."WORKER_CONTRACT_TYPES" as WCT on WCT."ID_WORKER_CONTRACT_TYPE" = W."ID_WORKER_CONTRACT_TYPE"
		LEFT JOIN "CONTRACT_MANAGEMENT"."WORKER_CONTRACT_TYPES_T" as WCTT on WCTT."ID_WORKER_CONTRACT_TYPE_T" = WCT."ID_WORKER_CONTRACT_TYPE_T"
		
		JOIN "CONTRACT_MANAGEMENT"."REL_SUPPLIER_WORKER" as RSW on RSW."ID_WORKER" = W."ID_WORKER"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS" as ATS on ATS."ID_ATTACHMENT_STATUS" = RSW."STATUS"
		LEFT JOIN "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS_T" as ATST on ATST."ID_ATTACHMENT_STATUS_T" = ATS."ID_ATTACHMENT_STATUS"
		
		JOIN "CONTRACT_MANAGEMENT"."SUPPLIERS" as S on S."ID_UNIQUE_SUP" = RSW."ID_UNIQUE_SUP"
		GROUP BY W.ID_WORKER, 
		         W.NAME, 
		         W.SURNAME,
                 W."DATE_BIRTH",     
                 W."GENDER",     
                 W."RESIDENCE",
                 W."CONTRACT_EXPIRED_DATE",
                 W."CUSTOM_ROLES",
                 W."CUSTOM_QUALIFICATIONS",
                 W."EU_CITIZEN",
                 W."DPI_III_LEVEL",
                 W."CREATED_BY",
                 W."CHANGED_BY", 
                 W."CREATED_DATE",
                 W."CHANGED_DATE",
                 WCT."ID_WORKER_CONTRACT_TYPE",
                 WCTT."TEXT",         
                 WCTT."SPRAS",          
                 RSW."ID_UNIQUE_SUP",    
                 RSW."VALIDATED_BY",
                 RSW."STATUS",
                 ATST."TEXT",
                 S."SUPPLIER_NAME";
   

/* Modifica V_REL_EQUIPMENT_CONTRACTS */
/* Relatione tra EQUIPMENT e CONTRACTS */
DROP VIEW V_REL_EQUIPMENT_CONTRACTS;
CREATE VIEW "V_REL_EQUIPMENT_CONTRACTS" 
AS
	SELECT DISTINCT
	    E."ID_EQUIPMENT"                 AS "IdEquipment",
	    E."DESCRIPTION"                  AS "DescriptionEquipment",
	    E."MANUFACTURER"                 AS "ManufacturerEquipment",
	    E."MODEL"                        AS "EquipmentModel",
	    E."YEAR_OF_COSTRUCTION"          AS "YoCEquipment",
	    E."EDUCATION_BOOKLET"            AS "EducationBookletEquipment",
	    E."MAINTENANCE_BOOKLET"          AS "MaintenanceBookletEquipment",
	    E."MATRICULAR_BOOKLET"           AS "MatricularBookletEquipment",
	    E."CE_BRAND"                     AS "CEBrandEquipment",
	    E."DECLARATION_OF_CONFORMITY"    AS "DeclarationOfConfEquipment",
	    E."ASL_SERIAL"                   AS "AslSerialEquipment",
	    E."EXTERNAL_VERIFICATION"        AS "ExternalVerificationEquipment",
        E."CREATED_BY"                   AS "CreatedBy",
        E."CHANGED_BY"                   AS "ChangedBy",
        E."CREATED_DATE"                 AS "CreatedDate",
        E."CHANGED_DATE"                 AS "ChangedDate",
        
	    RCE."ID_STATUS"                  AS "EquipmentStatus",
	    ASTT."TEXT"                      AS "EquipmentStatusText",
	    
        RCE."ID_UNIQUE_SUP"              AS "RelationIdSupplier",
	    RCE."APPROVAL_DATE"              AS "ApprovalDate",
	    RCE."APPROVAL_USER"              AS "ApprovalUser",

	    C."ID_CONTRACT"                  as "IdContract",
	    C."PERIMETER"                    as "ContractPerimeter",
	    C."SUBJECT"                      as "ContractSubject",
	    C."START_VALIDITY_DATE"          as "ContractStartValidityDate",
	    C."END_VALIDITY_DATE"            as "ContractEndValidityDate",
	    C."TOTAL_CONTRACT"               as "ContractTotal",
	    C."RES_CONTRACT"                 as "ContractRes",
	    C."DOC_DATE"                     as "ContractDocDate",
	    C."PERFECTION_DATE"              as "ContractPerfectionDate",
	    C."ID_UNIQUE_SUP"                as "ContractSupplier"
	    
		FROM "CONTRACT_MANAGEMENT"."EQUIPMENT" as E
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."REL_CONTRACT_EQUIPMENT" as RCE on RCE."ID_EQUIPMENT" = E."ID_EQUIPMENT"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACTS" as C on C."ID_CONTRACT" = RCE."ID_CONTRACT" and C."ID_UNIQUE_SUP" = RCE."ID_UNIQUE_SUP"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS" as AST on RCE."ID_STATUS" = AST."ID_ATTACHMENT_STATUS"
		LEFT JOIN "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS_T" as ASTT on ASTT."ID_ATTACHMENT_STATUS_T" = AST."ID_ATTACHMENT_STATUS_T";




/* Modifica V_REL_VEHICLE_CONTRACTS */
/* Relatione tra VEHICLE e CONTRACT */
DROP VIEW V_REL_VEHICLE_CONTRACTS;
CREATE VIEW "V_REL_VEHICLE_CONTRACTS" 
AS
	SELECT DISTINCT
	    W."ID_VEHICLES"                 AS "IdVehicles",
	    W."BRAND"                       AS "Brand",
	    W."ID_VEHICLES_TYPE"            AS "IdVehiclesType",
	    W."FILENAME_IMAGE"              AS "FileNameImageVehicle", 
        W."CREATED_BY"                  AS "VehiclesCreatedBy",
        W."CHANGED_BY"                  AS "VehiclesChangedBy",
        W."CREATED_DATE"                AS "VehiclesCreatedDate",
        W."CHANGED_DATE"                AS "VehiclesChangedDate",
	    
	    VTT."TEXT"                       AS "VehicleTypeText",
	    VTT."SPRAS"                      AS "VehicleTypeTextSpras",
	    
	    RCW."ID_STATUS"                  AS "VehicleStatus",
	    RCW."ID_UNIQUE_SUP"              AS "RelationIdSupplier",
	    RCW."APPROVAL_DATE"              AS "ApprovalDate",
	    RCW."APPROVAL_USER"              AS "ApprovalUser",
	    
	    ASTT."TEXT"                      AS "VehicleStatusText", 
	    
	    C."ID_CONTRACT"                  as "IdContract",
	    C."PERIMETER"                    as "ContractPerimeter",
	    C."SUBJECT"                      as "ContractSubject",
	    C."START_VALIDITY_DATE"          as "ContractStartValidityDate",
	    C."END_VALIDITY_DATE"            as "ContractEndValidityDate",
	    C."TOTAL_CONTRACT"               as "ContractTotal",
	    C."RES_CONTRACT"                 as "ContractRes",
	    C."DOC_DATE"                     as "ContractDocDate",
	    C."PERFECTION_DATE"              as "ContractPerfectionDate",
	    C."ID_UNIQUE_SUP"                  as "ContractSupplier"
	    
		FROM "CONTRACT_MANAGEMENT"."VEHICLES" as W
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."REL_CONTRACT_VEHICLE" as RCW on RCW."ID_VEHICLE" = W."ID_VEHICLES"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."VEHICLES_TYPES" as VT on VT."ID_VEHICLES_TYPE" = W."ID_VEHICLES_TYPE"
		LEFT JOIN "CONTRACT_MANAGEMENT"."VEHICLES_TYPES_T" as VTT on VTT."ID_VEHICLES_TYPES_T" = VT."ID_VEHICLES_TYPES_T"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACTS" as C on C."ID_CONTRACT" = RCW."ID_CONTRACT" and C."ID_UNIQUE_SUP" = RCW."ID_UNIQUE_SUP"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS" as ATS on ATS."ID_ATTACHMENT_STATUS" = RCW."ID_STATUS"
		LEFT JOIN "CONTRACT_MANAGEMENT"."ATTACHMENT_STATUS_T" as ASTT on ASTT."ID_ATTACHMENT_STATUS_T" = ATS."ID_ATTACHMENT_STATUS_T";
		


/* Modifica V_REL_GROUP_SUPERVISORS */
/* Relatione tra CS e GROUP */
DROP VIEW V_REL_GROUP_SUPERVISORS;
CREATE VIEW "V_REL_GROUP_SUPERVISORS" 
AS
SELECT DISTINCT
	    RUA."ID_UB"                     AS "IdUb",
	    RUA."UB_DESC"                   AS "UbDesc",
	    RUA."AFNAM"                     AS "Afnam",
	    RUA."AFNAM_DESC"                AS "AfnamDesc",
	    RUA."PLANT"                     AS "Plant",
	    RUA."PLANT_DESC"                AS "PLANTDESC",
	   
	    CS."ID_CONTRACT_SUPERVISORS"    AS "ID_CONTRACT_SUPERVISORS",
	    CS."NAME"                       AS "NAME",
	    CS."SURNAME"                    AS "SURNAME",
	    CS."IS_CS"                      AS "IS_CS",
	    CS."IS_ASSISTANT_CS_SIC"        AS "IS_ASSISTANT_CS_SIC",
	    CS."IS_ASSISTANT_CS_AMM"        AS "IS_ASSISTANT_CS_AMM",
	    CS."IS_ASSISTANT_CS_MAN"        AS "IS_ASSISTANT_CS_MAN",
	    
	    RGC."ID_GROUP"                    AS "IdGroup",
	    G."NAME"                         AS "GroupName",
	    G."DESCRIPTION"                   AS "GroupDescription",
	    G."WORK_CENTER"                   AS "WorkerCenter",
	    
	    RGC.IS_TEAM_LEADER              AS "TeamLeader"
	    
		FROM "CONTRACT_MANAGEMENT"."REL_USER_UB" as RUU
		JOIN"CONTRACT_MANAGEMENT"."REL_UB_TO_AFNAM" as RUA on RUU."ID_UB" = RUA."ID_UB"
		JOIN "CONTRACT_MANAGEMENT"."CONTRACT_SUPERVISORS" as CS on CS."ID_CONTRACT_SUPERVISORS" = RUU."USERMANE"
		JOIN "CONTRACT_MANAGEMENT"."GROUPS" as G on RUA."PLANT" = G."PLANT"
		LEFT JOIN "CONTRACT_MANAGEMENT"."REL_GROUPS_CS" as RGC on RGC."ID_GROUP" = G."ID_GROUP" AND RGC."ID_CS" = RUU."USERMANE";
		

-- modifica view V_REL_PLANT_COMMON_DOC
DROP VIEW V_RA_DAILY_DETAIL;
CREATE VIEW "V_RA_DAILY_DETAIL"    
AS
	SELECT DISTINCT
	    RDH."UUID_RA_DAILY_HEAD" AS "UuidRaDailyHead",
	    RDH."CS_DESCRIPTION" AS "CsDescription",
	    RDH."ODA" AS "OdA",
	    RDH."ID_CONTRACT" AS "IdContract",
	    RDH."PLANT" AS "Plant",
	    RDH."DATE" AS "Date",
	    RDH."DOCUMENT_NAME" AS "DocumentName",
	    RDH."ID_RA_DAILY_STATE" AS "IdRaDailyState",
		
	    RDH."SAVE_AND_SEND_BY" AS "SaveAndSendBy",
	    RDH."SAVE_AND_SEND_AT" AS "SaveAndSendAt",
	    RDH."IS_SUPPLIER_RA" AS "IsSupplierRa",
		RDH."UUID_SUPPLIER_RA_HEAD" AS "ExtendedUuidRaDailyHead",
	    RDH."UUID_GDL" AS "UuidGdL",
	    RDH."CREATED_BY" AS "RaHeadCreatedBy",
	    RDH."CREATED_AT" AS "RaHeadCreatedAt",
		
	    RDST."TEXT" AS "RaDailyStateDesc",
	    RDST."SPRAS" AS "RaDailyStateSpras",
	    
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."UUID_SUPPLIER_RA_DETAIL" AS "ExtendedUuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CREATED_BY" AS "CreatedBy",
	    RDD."CREATED_AT" AS "CreatedAt",
	    RDD."ID_RA_DAILY_ODMOP_STATES" AS "IdOdMOperationStatus",
	    RDD."TOTAL_ACCOUNTING" AS "TotalAccounting",
	    RDD."CURRENCY_TOT" AS "TotalCurrency",
	    RDOST."TEXT" AS "OdMOperationStatusDesc",
	    RDOST."SPRAS" AS "OdMOperationStatusSpras",
	    
	    ROOC."ODM_DESCRIPTION" AS "OdMDescription",
	    ROOC."OPERATION_DESCRIPTION" AS "OdMOperationDescription"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_HEAD" as RDH
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_STATES_T" as RDST on RDH."ID_RA_DAILY_STATE" = RDST."ID_RA_DAILY_STATE"
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD on RDH."UUID_RA_DAILY_HEAD" = RDD."UUID_RA_DAILY_HEAD"
		LEFT JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_ODMOP_STATES_T" as RDOST on RDD."ID_RA_DAILY_ODMOP_STATES" = RDOST."ID_RA_DAILY_ODMOP_STATES"
		LEFT JOIN "CONTRACT_MANAGEMENT"."REL_ODM_ODA_CONTRACT" as ROOC on ROOC."ID_ODM" = RDD."ID_ODM" AND ROOC."ID_ODM_OPERATION" = RDD."ID_ODM_OPERATION";

-- modifica view V_REL_PLANT_COMMON_DOC
DROP VIEW V_REL_PLANT_COMMON_DOC;
CREATE VIEW "V_REL_PLANT_COMMON_DOC"    
AS
	SELECT DISTINCT
	    CD."ID_COMMON_DOCUMENTS"   AS "IdCommonDocument",
	    CD."ID_DOC_TYPES"   AS "IdDocType",
	    CD."TITLE"   AS "Title",
	    CD."DESCRIPTION"   AS "Description",
	     
	    RPCD."PLANT"  AS "Plant"
	   
		FROM "CONTRACT_MANAGEMENT"."REL_PLANT_COMMON_DOC2" as RPCD
		JOIN "CONTRACT_MANAGEMENT"."COMMON_DOCUMENTS" as CD on RPCD."ID_COMMON_DOCUMENTS" = CD."ID_COMMON_DOCUMENTS";

-- modifica view V_CONTRACT_TO_CS_FOR_GDL
DROP VIEW V_CONTRACT_TO_CS_FOR_GDL;
CREATE VIEW "V_CONTRACT_TO_CS_FOR_GDL"
AS
	SELECT DISTINCT
	
	    C."ID_CONTRACT"                       AS "IdContract",
	    C."SUBJECT"                           AS "ContractSubject",
	    C."PLANT"                             AS "Plant",
	    
		S."SUPPLIER_NAME"                     AS "SupplierName",
		S."ID_SUPPLIER"                       AS "CodFornitore",
		
		CS."NAME"                             AS "CSName",
		CS."SURNAME"                          AS "CSSurname",
		CS."ID_CONTRACT_SUPERVISORS"          AS "CSId",
		CAD."IS_CS_MAIN"   					  AS "CSIsCSMain",
		
		GS."ID_GREEN_SHEET"                   AS "IdGreenSheet",
		GS."MODIFIED_DOC"                     AS "GreenSheetModifiedDoc",
		
		ROOC."ODA"                            AS "Oda",
		ROOC."ODA_DESCRIPTION"                AS "OdaDescription",
		ROOC."CS_DESCRIPTION"                 AS "RelOdMOdAContractCsDescription"
		
		FROM "CONTRACT_MANAGEMENT"."CONTRACTS" as C
		
		JOIN "CONTRACT_MANAGEMENT"."SUPPLIERS" as S on S."ID_UNIQUE_SUP" = C."ID_UNIQUE_SUP"
	
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATIONS" as CA on CA."ID_CONTRACT" = C."ID_CONTRACT"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_ASSOCIATION_DETAILS" as CAD on CAD."ID_CONTRACT_ASSOCIATION" = CA."ID_CONTRACT_ASSOCIATION"
		
		LEFT JOIN "CONTRACT_MANAGEMENT"."CONTRACT_SUPERVISORS" as CS on CS."ID_CONTRACT_SUPERVISORS" = CAD."ID_CONTRACT_SUPERVISORS"

		LEFT JOIN "CONTRACT_MANAGEMENT"."GREEN_SHEETS" as GS on C."ID_CONTRACT" = GS."ID_CONTRACT"
		
		JOIN "CONTRACT_MANAGEMENT"."REL_ODM_ODA_CONTRACT" as ROOC on C."ID_CONTRACT" = ROOC."ID_CONTRACT"

		WHERE CA."IS_ACTIVE_VERSION" = '1' AND (
		    GS."ID_GREEN_SHEET" IS NULL OR 
		    ( 
		        NOT GS."ID_GREEN_SHEET" IS NULL AND
		        GS."IS_ACTIVE_VERSION" = '1'AND
		        C."ID_UNIQUE_SUP" = GS."ID_UNIQUE_SUP"
		    )
 	      );
 	      
-- modifica view ra daily detail workers
DROP VIEW V_RA_DAILY_DETAIL_WORKERS;
CREATE VIEW "V_RA_DAILY_DETAIL_WORKERS"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDW."UUID_RA_DAILY_DETAIL_WORKER" AS "UuidRaDailyDetailWorker",
	    RDDW."ID_WORKER" AS "IdWorker",
	    RDDW."TIME1_BEG" AS "Time1Beg",
	    RDDW."TIME1_END" AS "Time1End",
	    RDDW."TIME2_BEG" AS "Time2Beg",
	    RDDW."TIME2_END" AS "Time2End",
	    RDDW."TIME_BREAK" AS "TimeBreak",
	    RDDW."TOTAL_HOURS" AS "TotalHours",
	    RDDW."CREATED_AT" AS "CreatedAt",
	    RDDW."CREATED_BY" AS "CreatedBy",
		RDDW."IS_DELETED" AS "IsDeleted",

	    W."NAME" AS "name",
	    W."SURNAME" AS "surname",
	    W."CONTRACT_EXPIRED_DATE" AS "contractExpiredDate",
	    
	    QT.TEXT AS "Qualifition"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_WORKER" as RDDW on RDD."UUID_RA_DAILY_DETAIL" = RDDW."UUID_RA_DAILY_DETAIL"
		JOIN "CONTRACT_MANAGEMENT"."WORKERS" as W on RDDW."ID_WORKER" = W."ID_WORKER"
		LEFT JOIN "CONTRACT_MANAGEMENT"."REL_WORKER_QUALIFICATIONS" as RWQ on RWQ."ID_WORKER" = W."ID_WORKER"
		LEFT JOIN "CONTRACT_MANAGEMENT"."QUALIFICATIONS" as Q on Q."ID_QUALIFICATION" = RWQ."ID_QUALIFICATION"
		LEFT JOIN "CONTRACT_MANAGEMENT"."QUALIFICATIONS_T" as QT on QT."ID_QUALIFICATION_T" = Q."ID_QUALIFICATION_T";
		
-- modifica view ra daily detail workers non core
DROP VIEW V_RA_DAILY_DETAIL_WORKER_NONCORE;
CREATE VIEW "V_RA_DAILY_DETAIL_WORKER_NONCORE"    
AS
	SELECT DISTINCT
	    RDDWNS."UUID_RA_DAILY_HEAD_WORKER" AS "UUID_RA_DAILY_HEAD_WORKER",
	    RDDWNS."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
	    RDDWNS."ID_WORKER" AS "ID_WORKER",
	    RDDWNS."TIME1_BEG" AS "TIME1_BEG",
	    RDDWNS."TIME1_END" AS "TIME1_END",
	    RDDWNS."TIME2_BEG" AS "TIME2_BEG",
	    RDDWNS."TIME2_END" AS "TIME2_END",
	    RDDWNS."TIME_BREAK" AS "TIME_BREAK",
	    RDDWNS."CREATED_AT" AS "CREATED_AT",
	    RDDWNS."CREATED_BY" AS "CREATED_BY",
		RDDWNS."IS_DELETED" AS "IsDeleted",
		RDDWNS.TOTAL_HOURS  AS "TOTAL_HOURS", 

	    W."NAME" AS "name",
	    W."SURNAME" AS "surname",
	    W."CONTRACT_EXPIRED_DATE" AS "contractExpiredDate",
	    
	    QT.TEXT AS "Qualifition"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_WORKER_NONCORE_SERVICES" as RDDWNS
		JOIN "CONTRACT_MANAGEMENT"."WORKERS" as W on RDDWNS."ID_WORKER" = W."ID_WORKER"
		LEFT JOIN "CONTRACT_MANAGEMENT"."REL_WORKER_QUALIFICATIONS" as RWQ on RWQ."ID_WORKER" = W."ID_WORKER"
		LEFT JOIN "CONTRACT_MANAGEMENT"."QUALIFICATIONS" as Q on Q."ID_QUALIFICATION" = RWQ."ID_QUALIFICATION"
		LEFT JOIN "CONTRACT_MANAGEMENT"."QUALIFICATIONS_T" as QT on QT."ID_QUALIFICATION_T" = Q."ID_QUALIFICATION_T";

		
-- modifica view ra daily detail vehicle
DROP VIEW V_RA_DAILY_DETAIL_VEHICLE;
CREATE VIEW "V_RA_DAILY_DETAIL_VEHICLE"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDV."UUID_RA_DAILY_DETAIL_VEHICLE" AS "UuidRaDailyDetailVehicle",
	    RDDV."ID_VEHICLE" AS "IdVehicle",
	    RDDV."TIME1_BEG" AS "Time1Beg",
	    RDDV."TIME1_END" AS "Time1End",
	    RDDV."TIME2_BEG" AS "Time2Beg",
	    RDDV."TIME2_END" AS "Time2End",
	    RDDV."TIME_BREAK" AS "TimeBreak",
	    RDDV."TOTAL_HOURS" AS "TotalHours",
	    RDDV."CREATED_AT" AS "CreatedAt",
	    RDDV."CREATED_BY" AS "CreatedBy",
		RDDV."IS_DELETED" AS "IsDeleted",
		
	    V."BRAND" AS "Brand",
	    
	    VTT."TEXT" AS "TypeText"
	    
		
		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_VEHICLE" as RDDV on RDD."UUID_RA_DAILY_DETAIL" = RDDV."UUID_RA_DAILY_DETAIL"
		JOIN "CONTRACT_MANAGEMENT"."VEHICLES" as V on RDDV."ID_VEHICLE" = V."ID_VEHICLES"
		LEFT JOIN "CONTRACT_MANAGEMENT"."VEHICLES_TYPES" as VT on VT."ID_VEHICLES_TYPE" = V."ID_VEHICLES_TYPE"	
		JOIN "CONTRACT_MANAGEMENT"."VEHICLES_TYPES_T" as VTT on VTT."ID_VEHICLES_TYPES_T" = VT."ID_VEHICLES_TYPES_T" WHERE (VTT."SPRAS" = 'IT');
		
-- modifica view ra daily detail vehicle non core
DROP VIEW V_RA_DAILY_DETAIL_VEHICLE_NONCORE;
CREATE VIEW "V_RA_DAILY_DETAIL_VEHICLE_NONCORE"    
AS
	SELECT DISTINCT
	    RDDVNS."UUID_RA_DAILY_HEAD_VEHICLE" AS "UUID_RA_DAILY_HEAD_VEHICLE",
	    RDDVNS."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
	    RDDVNS."ID_VEHICLE" AS "ID_VEHICLE",
	    RDDVNS."TIME1_BEG" AS "TIME1_BEG",
	    RDDVNS."TIME1_END" AS "TIME1_END",
	    RDDVNS."TIME2_BEG" AS "TIME2_BEG",
	    RDDVNS."TIME2_END" AS "TIME2_END",
	    RDDVNS."TIME_BREAK" AS "TIME_BREAK",
	    RDDVNS."CREATED_AT" AS "CREATED_AT",
	    RDDVNS."CREATED_BY" AS "CREATED_BY",
		RDDVNS."IS_DELETED" AS "IsDeleted",
		RDDVNS.TOTAL_HOURS  AS "TOTAL_HOURS", 
	    
	    V."BRAND" AS "BRAND",
	    
	    VTT."TEXT" AS "TypeText"
	    

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_VEHICLE_NONCORE_SERVICES" as RDDVNS
		JOIN "CONTRACT_MANAGEMENT"."VEHICLES" as V on RDDVNS."ID_VEHICLE" = V."ID_VEHICLES"
		LEFT JOIN "CONTRACT_MANAGEMENT"."VEHICLES_TYPES" as VT on VT."ID_VEHICLES_TYPE" = V."ID_VEHICLES_TYPE"	
		JOIN "CONTRACT_MANAGEMENT"."VEHICLES_TYPES_T" as VTT on VTT."ID_VEHICLES_TYPES_T" = VT."ID_VEHICLES_TYPES_T" WHERE (VTT."SPRAS" = 'IT');
		
-- Modifica view ra non core equipment
DROP VIEW V_RA_DAILY_DETAIL_EQUIPMENT_NONCORE;
CREATE VIEW "V_RA_DAILY_DETAIL_EQUIPMENT_NONCORE"    
AS
	SELECT DISTINCT
	    RDDENS."UUID_RA_DAILY_HEAD_EQUIPMENT" AS "UUID_RA_DAILY_HEAD_EQUIPMENT",
	    RDDENS."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
	    RDDENS."ID_EQUIPMENT" AS "ID_EQUIPMENT",
	    RDDENS."TIME1_BEG" AS "TIME1_BEG",
	    RDDENS."TIME1_END" AS "TIME1_END",
	    RDDENS."TIME2_BEG" AS "TIME2_BEG",
	    RDDENS."TIME2_END" AS "TIME2_END",
	    RDDENS."TIME_BREAK" AS "TIME_BREAK",
	    RDDENS."CREATED_AT" AS "CREATED_AT",
	    RDDENS."CREATED_BY" AS "CREATED_BY",
		RDDENS."IS_DELETED" AS "IsDeleted",
		RDDENS.TOTAL_HOURS  AS "TOTAL_HOURS", 
	    
	    E."DESCRIPTION" AS "DESCRIPTION",
	    E."MANUFACTURER" AS "MANUFACTURER",
	    E."MODEL" AS "MODEL"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_EQUIPMENT_NONCORE_SERVICES" as RDDENS
		JOIN "CONTRACT_MANAGEMENT"."EQUIPMENT" as E on RDDENS."ID_EQUIPMENT" = E."ID_EQUIPMENT";	
		
-- Modifica V_RA_DAILY_DETAIL_ATTACH
DROP VIEW V_RA_DAILY_DETAIL_ATTACH;
CREATE VIEW "V_RA_DAILY_DETAIL_ATTACH"    
AS
	SELECT DISTINCT
	    RDD."UUID_RA_DAILY_DETAIL" AS "UuidRaDailyDetail",
	    RDD."ID_ODM" AS "IdOdM",
	    RDD."ID_ODM_OPERATION" AS "IdOdMOperation",
	    RDD."CS_DESCRIPTION" AS "CsDescription",

	    RDDA."UUID_RA_DAILY_DETAIL_ATTACH" AS "UuidRaDailyDetailAttach",
	    RDDA."DOCUMENTAL_FILENAME" AS "DocumentalFilename",
	    RDDA."FILE_LOCATION" AS "FileLocation",
	    RDDA."FILENAME" AS "Filename",
	    RDDA."UPLOADED_BY" AS "UploadedBy",
	    RDDA."UPLOADED_AT" AS "UploadedAt",
	    RDDA."IS_DELETED" AS "IsDeleted",
	    RDDA."UUID_SUPPLIER_RA_DETAIL_ATTACH" AS "UuidSupplierRaDetailAttach"

		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_DETAILS" as RDD
		JOIN "CONTRACT_MANAGEMENT"."RA_DAILY_DETAIL_ATTACH" as RDDA on RDD."UUID_RA_DAILY_DETAIL" = RDDA."UUID_RA_DAILY_DETAIL";		
		
		
CREATE VIEW "V_RA_DAILY_HEAD_FOR_CALENDAR_GDL"    
AS
	SELECT DISTINCT
        RDH."UUID_RA_DAILY_HEAD" AS "UUID_RA_DAILY_HEAD",
        RDH."CS_DESCRIPTION" AS "CS_DESCRIPTION",
        RDH."ODA" AS "ODA",
        RDH."ID_CONTRACT" AS "ID_CONTRACT", 
        RDH."PLANT" AS "PLANT",
        RDH."ID_SUPPLIER" AS "ID_SUPPLIER",
        RDH."DATE" AS "DATE",
        RDH."DOCUMENT_NAME" AS "DOCUMENT_NAME",
        RDH."ID_RA_DAILY_STATE" AS "ID_RA_DAILY_STATE",
        RDH."SAVE_AND_SEND_BY" AS "SAVE_AND_SEND_BY",
        RDH."SAVE_AND_SEND_AT" AS "SAVE_AND_SEND_AT",
        RDH."IS_SUPPLIER_RA" AS "IS_SUPPLIER_RA",
        RDH."UUID_SUPPLIER_RA_HEAD" AS "UUID_SUPPLIER_RA_HEAD",
        RDH."CREATED_BY" AS "CREATED_BY",
        RDH."CREATED_AT" AS "CREATED_AT",
        RDH."UUID_GDL" AS "UUID_GDL",
        
        GDL."CREATED_BY" as "GDL_CREATED_BY",
        GDL."CREATED_AT" as "GDL_CREATED_AT",
        GDL."DOCUMENT_NAME" as "GDL_DOCUMENT_NAME",
        GDL."ID_GDL_STATUS" as "ID_GDL_STATUS",
        GDLST."ID_GDL_STATUS_T" as "ID_GDL_STATUS_T",
        
        GDLST."TEXT" as "GDL_STATUS_TEXT",
        GDLST."SPRAS" as "GDL_STATUS_SPRAS"
        
		FROM "CONTRACT_MANAGEMENT"."RA_DAILY_HEAD" as RDH
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL" as GDL on RDH."UUID_GDL" = GDL."UUID_GDL"
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS" as GDLS on GDL."ID_GDL_STATUS" = GDLS."ID_GDL_STATUS"		
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS_T" as GDLST on GDLS."ID_GDL_STATUS_T" = GDLST."ID_GDL_STATUS_T"
		
		WHERE GDL."IS_ACTIVE_VERSION" = '1' 
		OR (RDH."UUID_GDL" IS NULL OR RDH."UUID_GDL" = '');
		
CREATE VIEW "V_GDL_FOR_CALENDAR_GDL"    
AS
	SELECT DISTINCT
        GDL."UUID_GDL" AS "UUID_GDL",
        GDL."ID_GDL_STATUS" AS "ID_GDL_STATUS",
        GDL."START_DATE" AS "START_DATE",
        GDL."END_DATE" AS "END_DATE",
        GDL."CREATED_BY" AS "CREATED_BY",
        GDL."CREATED_AT" AS "CREATED_AT",
        GDL."DOCUMENT_NAME" AS "DOCUMENT_NAME",
        GDL."ID_CONTRACT" AS "ID_CONTRACT",
        GDL."ODA" AS "ODA",
        GDL."IS_SUPPLIER_VERSION" AS "IS_SUPPLIER_VERSION",
        GDL."FILENAME" AS "FILENAME",
        GDL."VERSION" AS "VERSION",
        GDL."IS_ACTIVE_VERSION" AS "IS_ACTIVE_VERSION",
        GDLST."ID_GDL_STATUS_T" as "ID_GDL_STATUS_T",
        GDLST."TEXT" as "GDL_STATUS_TEXT",
        GDLST."SPRAS" as "GDL_STATUS_SPRAS"
        
		FROM  "CONTRACT_MANAGEMENT"."GDL" as GDL
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS" as GDLS on GDL."ID_GDL_STATUS" = GDLS."ID_GDL_STATUS"		
		LEFT JOIN "CONTRACT_MANAGEMENT"."GDL_STATUS_T" as GDLST on GDLS."ID_GDL_STATUS_T" = GDLST."ID_GDL_STATUS_T";